### ISSUE TITLE
Help for token settings in configuration.js

### ISSUE THREAD

**Issue by nikolaiiii** [ziahamza/webui-aria2#114]
Hello, maybe I didn't understand the principle of the configuration.js file hosted on the web server, but even if I setup the auth token in this file, the Web interface can't connect to the aria2c port. I have to manually edit the connection settings through the webui in order to be able to connect to the RPC interface.

Or maybe is it the syntax of the token which is incorrect? Actually I have something like this: 

auth: {
   token: 'my_super_token',
  }

Any hint would be much appreciated.

Thanks,
Nicolas

**Comment by SRChiP** [comment]
I know this is an old issue, but one solution I found was that if the webui & rpc is on the same server/ip, you can simply use, 
host: window.location.hostname
