### ISSUE TITLE
Status of download launched by CLI with aria2c as daemon

### ISSUE THREAD

**Issue by nikolaiiii** [ziahamza/webui-aria2#115]
Hello, I would like to know if it is possible to configure webui-aria2 to check the status of current downloads (especially torrents) which would have been launched through the aria2c command line (with aria2c running as a daemon)?

For example, if I launch the command "aria2c myfile.torrent", currently I can't see the download when I connect to the webui interface.

If this is already possible, what is the best way to do this?

Thank you.
Nicolas

**Comment by jdarias** [comment]
@nikolaiiii When you run aria2c --enable-rpc you are invoking a an aria2 daemon instance that will accept downloads from the webui or from any means that can comunicate with it via its rpc interface. For example the webui or the aria2rpc.rb script, or any other aria2 frontend software.

If after running aria2c --enable-rpc you run "aria2c myfile.torrent" you will be invoking a completely independent instance of aria2 that will proccess the myfile.torrent download. This instance wont be able to report to your already running daemon, nor will the daemon be able to get info from it.

So if you want to see reports from the webui add the downloads in the webui, or use a rpc enabled frontend like the ones mentioned.

**Comment by nikolaiiii** [comment]
Hi @jdarias , thank you for your explanation, it is much appreciated.

**Comment by nikolaiiii** [comment]
Hi @jdarias , thank you for your explanation, it is much appreciated.
