### ISSUE TITLE
enable rpc

### ISSUE THREAD

**Issue by yas9999** [ziahamza/webui-aria2#116]
Hello,
i have an issue, i have to run each time aria2c --enable-rpc --rpc-listen-all manually
there is any solution to make it automatically run !

Best regards

**Comment by jdarias** [comment]
@yas9999 Use NSSM https://nssm.cc/ to set aria2 as a service. You have to give permissions to the local service account for the download folder.

**Comment by yas9999** [comment]
thank you @jdarias :+1:
