### ISSUE TITLE
rpc-secret password isn't retained

### ISSUE THREAD

**Issue by gbcox** [ziahamza/webui-aria2#125]
I put the password into connection settings:
enter the secret token.  I press save.
Everything works fine... but after a period of time, the password disappears, the connection drops and I have to re-enter and then save it.  
I was able to manually edit the configuration.js file which got things working, as far as I can tell however the connection settings dialog doesn't write to the configuration.js file.

Also, did you think of just getting the password from the aria2.conf file?  

If there is anymore information you need, let me know.  Thanks!

**Comment by ziahamza** [comment]
I have to look into this. Webui cannot really read the aria2.conf as it lives in the server and is not accessible from the browser for security reasons.

-----Original Message-----

**Comment by gbcox** [comment]
Understood.  In my particular situation I am using a single server that runs both the Webui and aria2.  I also opened an issue with aria2:  https://github.com/tatsuhiro-t/aria2/issues/329
regarding having the rpc-secret in plain text and suggested they look at the method used by the msmtp project as additional option: http://msmtp.sourceforge.net/doc/msmtp.html#passwordeval

It just doesn't seem quite right to have something called "rpc-secret" and then have it stored in plain text in every application that uses aria2 (including the aria2 conf).

**Comment by ziahamza** [comment]
Oh nice. I will follow the issue as it comes along

-----Original Message-----

**Comment by louy2** [comment]
I'm thinking about how normal web server handles password validation: hashed store, hash validation, cookie for session persistence, etc.

**Comment by ziahamza** [comment]
Yeah, giving it a hash rather then plain text password makes more sense. Then webui can just hash the password in place and send it off to aria2 without leaking it.

**Comment by louy2** [comment]
Nvm, aria2 isn't normal web server and doesn't come with cookie and such, and the webui can do little to enhance that.

@gbcox 
IMO the webUI is only providing UI, so your current setting should be fine as long as you use a safe password, you know, random with symbols, no dictionary words. The true securing should be at the server with which you serve the webUI, e.g., you can require a user certificate to access it with nginx.

**Comment by alexya** [comment]
@gbcox Hi, I ran the aria2 in my local machine and met the same issue as you. You mentioned that:
```
I was able to manually edit the configuration.js file which got things working, as far as I can tell however the connection settings dialog doesn't write to the configuration.js file.
```
Could u please give me help on how to edit the configuration.js file to add the token and make it work. 
I did like this in the configuration.js, but failed to work. 
```
  .constant("$authconf", {
    // default authentication configuration, never fill it in case the webui is hosted in public IP as it can be compromised
    host: location.protocol.startsWith("http") ? location.hostname : "localhost",
    path: "/jsonrpc",
    port: 6800,
    encrypt: false,
    auth: {
      token: 'my_token_here'
      // either add the token field or the user and pass field, not both.
      // token: '$YOUR_SECRET_TOKEN$'
      /*-----------------------------*/
      // user: '*YOUR_USERNAME*',
      // pass: '*YOUR_SECRET_PASS*'
    },
    directURL: "" // If supplied, links will be created to enable direct download from the aria2 server, requires appropriate webserver to be configured
  })
```

**Comment by no1xsyzy** [comment]
@alexya try <https://github.com/ziahamza/webui-aria2/issues/473#issuecomment-427974866>, `configuration.js` does not work before compiling.
Otherwise you can try #417.
