### ISSUE TITLE
Download completed downloads

### ISSUE THREAD

**Issue by Yamakaky** [ziahamza/webui-aria2#128]
Sorry, I couldn't find a better title ^^
It doesn't seem to be possible to download a downloaded file via http. It would be nice, for example with an aria2 session running on a seedbox. You add a torrent/http/whatever on the server, it's downloaded, then you fetch it on your laptop using webui. Seems legit ?
Yamakaky

**Comment by ziahamza** [comment]
IT wont really be possible. This project talks to aria2 over the API it
provides, and it doesnt give access to the downloaded files. You can try to
add this feature in the aria2 project itself.

**Comment by Yamakaky** [comment]
Ok.
