### ISSUE TITLE
The parameter at 0 has wrong type

### ISSUE THREAD

**Issue by svebue** [ziahamza/webui-aria2#129]
Hi Guys,

after installation aria2 on my Rasp, i would connect via webui to the server.
The gui sends after the message "Successfully connected to Aria2 through its remote RPC …" allways the error "the paramter at 0 has wrong type".

Where is my fault?
Greetz svebue

**Comment by ziahamza** [comment]
hmm ... it could be because you may be running an old version of Aria2.
What version of aria2 are you using?

**Comment by svebue** [comment]
He ziahamza,

the settings are the following:

Aria2 Version 1.15.1 

Features Enabled
Async DNS
BitTorrent
Firefox3 Cookie
GZip
HTTPS
Message Digest
Metalink
XML-RPC

**Comment by rafaelvieiras** [comment]
I installed aria2 via apt-get, but this installed version 1.15.1 In webui show this version.
After i download source code and compiled via ```$ make install```, its okey. Run command ```$ aria2c --version``` and this show 1.18.10 version, but in webui still show version 1.15.1.

Console:
```
root@raspberrypi:~# aria2c --version
aria2 version 1.18.10
Copyright (C) 2006, 2014 Tatsuhiro Tsujikawa

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

** Configuration **
Enabled Features: BitTorrent, Message Digest
Hash Algorithms: sha-1, sha-224, sha-256, sha-384, sha-512, md5
Libraries:
Compiler: gcc 4.6.3
  built by   armv6l-unknown-linux-gnueabihf
  on         Apr 22 2015 04:31:52
System: Linux 3.18.7+ #755 PREEMPT Thu Feb 12 17:14:31 GMT 2015 armv6l

Report bugs to https://github.com/tatsuhiro-t/aria2/issues
Visit http://aria2.sourceforge.net/
```
Webui:
```
Aria2 server info

Aria2 Version 1.15.1 

Features Enabled
Async DNS
BitTorrent
Firefox3 Cookie
GZip
HTTPS
Message Digest
Metalink
XML-RPC
```

Whats going on? I receive this message ever ""the paramter at 0 has wrong type"."

**Comment by ziahamza** [comment]
What command do you guys use to run aria2. I will try to replicate this
error.

Is it just:
aria2c --enable-rpc

or you guys add more options?

**Comment by rafaelvieiras** [comment]
I run using ```aria2c --enable-rpc --rpc-listen-all```.
Now it work for me.
After compiled source code, i remove old installing via ```apt-get``` using ```apt-get purge aria2c```. Thanks :smile:

**Comment by ziahamza** [comment]
Awesome!! I also thought it was an aria2 version issue. Closing the issue
