### ISSUE TITLE
webUI connexion to aria2c RPC

### ISSUE THREAD

**Issue by cazzoo** [ziahamza/webui-aria2#13]
Hi there,

According to your previous post in aria2c forums ( https://sourceforge.net/apps/phpbb/aria2/viewtopic.php?f=1&t=195&p=982#p982 ).

I' tried your solutions to try to get webui working with my debian aria2c server.

Here is a summary :

► Debian server running 24/7 and hosting aria2c and webserver (apache2).
► aria2c running with startup script (see this post : https://sourceforge.net/apps/phpbb/aria2/viewtopic.php?f=1&t=196&p=961#p961 ), running with RPC (with user and pass filled in)
► webui-aria2 www folder located in /var/www/ and sync with git (git pull)
► port 6800 open in my router and forwarded to my server
► Iptables allowing traffic

I open up the webui from github and tried to connect to my aria2c server entering with my external IP, RPC user and RPC pass >> No result
I open up the webui hosted in my debian server with local IP (192.168.1.x) and set server IP, RPC user and RPC pass >> No result
I stopped my actual aria2c daemon and started with only "aria2c --enable-rpc", tried both github page or local page with corresponding IP and without RPC user and RPC pass >> No result

This issue makes me feel really weird because It seems that my parameters seems right, but no results.

Also, got a notice : Could you make this sentences more explicit (or said in another way) : 
● Enter the username of the server on which the rpc for aria2 is running (empty if authentication not enabled)
● Enter the password of the server on which the rpc for aria2 is running (empty if authentication not enabled)

These sentences means that we need to enter server user and pass and not aria2c RPC user and RPC pass (otherwise, I'm totally wrong and these fields needs These infos)

**Comment by itised83** [comment]
Hi. Is anybody still here for questions about aria2 and the webui?

**Comment by mu3** [comment]
I can access **remote** aria2 rpc server only if I use `file:///…/webui-aria2/index.html`.
Can't access from https://ziahamza.github.io/webui-aria2/ or any other hosted webui-aria2 with exactly the same settings.
Any ideas?

**Comment by no1xsyzy** [comment]
@mu3 you should first check if your are running on https (I noticed that you have the github.io page url in https). `ws://` schema won't work if you are using the page through https (browsers' security restrictions). you can switch to `wss://` if you have a cert (configuration in aria2 and the checkbox in link settings).
If not even accessible from http pages, then red words from browser console will help (howto: [chrome](https://developers.google.com/web/tools/chrome-devtools/console/) / [firefox](https://developer.mozilla.org/en-US/docs/Tools/Browser_Console))
