### ISSUE TITLE
aria2.js

### ISSUE THREAD

**Issue by sonnyp** [ziahamza/webui-aria2#130]
Just to let you know I made a aria2 JavaScript library if you'd like to use/contribute to it.
https://github.com/sonnyp/aria2.js

**Comment by ziahamza** [comment]
The library looks good! I would love to use it, but the codebase already has its own library, and it supports some weird tricks to bypass some chrome restrictions on http authentication, which makes sure the project works even when you open it from the filesystem (file://...).

**Comment by ziahamza** [comment]
but I would love to work over the weekend sometime and port my codebase over to the new project and push any improvement to your project :)

**Comment by sonnyp** [comment]
@ziahamza thanks!

That'd be great, let me know if I can help or if you need anything.
