### ISSUE TITLE
 The newest version's ADD dialogues CANCEL and or START buttons are not on screen.

### ISSUE THREAD

**Issue by prodigalgvs** [ziahamza/webui-aria2#134]
The newest version's ADD dialogues CANCEL and or START buttons are down past the bottom of the screen and one has to scroll the browser window down to see them, or click on them.  It is annoying enough to not use :)

This is confirmed on two different resolution "widescreen" laptops:  16:9 1366x768, & 16:10 1440x1050

**Comment by ziahamza** [comment]
Just removed some description to make some more space. It shows up the dialog add buttons now on my Mac Air. Is it still out of bounds?

**Comment by prodigalgvs** [comment]
Yes, it is by at least five lines.  See screenshot.

Gordon VS
gvscheik1@cciwireless.ca
