### ISSUE TITLE
Add support to view errroCode in form of EXIT STATUS

### ISSUE THREAD

**Issue by shahril96** [ziahamza/webui-aria2#136]
Log is very useful if aria2c is falling to download files/torrents without any reasons inside web-ui, adding feature to view log file created by aria2c with --log=/to/file/ is very useful. An example of error can be file is already existed so aria2 will throw error with sign "[ERROR]" so it's easy to filter it out.

**Comment by shahril96** [comment]
Very sorry as webui-aria2 is build entirely with client-side in mind, so it can't just easily view log files. :(
But still, this section tells use that we can view error code through http://aria2.sourceforge.net/manual/en/html/aria2c.html#aria2.tellStatus and parse it so it's convient to the user.

**Comment by ziahamza** [comment]
Just landed this in master. Aria2 should now show error status codes :)
