### ISSUE TITLE
double-license?

### ISSUE THREAD

**Issue by zabbal** [ziahamza/webui-aria2#144]
Is it possible to license it as AGPLv3+ as well? It's more suitable for webservice-like things.

**Comment by ziahamza** [comment]
@zabbal sure? but I think MIT license gives you MUCH more freedom then AGLPv3+ anyways. Why did you ask specifically?

**Comment by no1xsyzy** [comment]
It is nonsense to inform the aria2 server that you are using a modified version of `webui-aria2`.
AGPL is meaningful only on the server-side software.
