### ISSUE TITLE
Remember files upon restart.

### ISSUE THREAD

**Issue by kdb424** [ziahamza/webui-aria2#147]
I have to re add all files that were downloading when I reboot my machine. The interface will not remember what it was doing if I stop the process and restart it. Is there any chance that you can add support for remembering files, or will I have to manually find the links/torrents each restart?

**Comment by ziahamza** [comment]
You should start aria2 with a configuration that makes sure that it can remember downloads. This project is just a UI on top of aria2


Sent by Outlook for Android





On Sat, May 16, 2015 at 11:08 AM -0700, "Kyle Brown" <notifications@github.com> wrote:












I have to re add all files that were downloading when I reboot my machine. The interface will not remember what it was doing if I stop the process and restart it. Is there any chance that you can add support for remembering files, or will I have to manually find the links/torrents each restart?

**Comment by jdarias** [comment]
Put this in your aria2.conf

# permitir salvar descargas BT en la sesion
bt-save-metadata=true
rpc-save-upload-metadata=true

# opciones de la sesion
# sessionfile.txt must exist beforehand. you can use any filename.
continue=true
input-file=sessionfile.txt
save-session=sessionfile.txt
save-session-interval=300
