### ISSUE TITLE
--check-certificate not working ?

### ISSUE THREAD

**Issue by PanDoreS** [ziahamza/webui-aria2#148]
Hi,

Thanks for your WebUI, it's working great.
However, I've got one issue with it.
I try to download files from my main server in HTTPS, but with a self-signed certificate.
I changed the '--check-certificate=false' settings in the "Global Settings", but every time I try to download a link, aria2 write in the terminal : 
05/19 13:36:45 [ERROR] CUID#46 - Download aborted. URI=https://ADDRESS/images/bg1.jpg
Exception: [AbstractCommand.cc:350] errorCode=1 URI=https://ADDRESS/images/bg1.jpg
  -> [SocketCore.cc:933] errorCode=1 SSL/TLS handshake failure: Invalid certificate chain

I tried to inject the command into /js/ctrls/modal.js at line 69 : "settings['check-certificate'] = 'false';", the settings is sent, but this doesn't resolve the issue.
I did the same thing to inject a "http-user" and "http-passwd" settings and it work.
Have you the same issue on your side ?

A fix I found is to force "--check-certificate=false" when I launch the aria2 command in the terminal.

Thanks !

**Comment by tatsuhiro-t** [comment]
aria2 uses check-certificate option in config file or initial command-line options only.  If it is given in RPC method or -i list, it is ignored.

**Comment by PanDoreS** [comment]
Oh, ok, my bad :smile: !
Thanks for your very fast answer !
