### ISSUE TITLE
can't find http-passwd in advance option

### ISSUE THREAD

**Issue by kraith** [ziahamza/webui-aria2#151]
when added download and click advance download option, i can't find http-passwd option
please help

**Comment by ziahamza** [comment]
Sorry for the late reply :/

I have pushed the support for http-passwd in the latest version, do you wanna download it again and check if it now works with http password protected downloads?

**Comment by kraith** [comment]
thank you for the reply
http-passw is there but how do i input my user credential 
maybe http-user is missing too
sorry im really new about linux, and pardon my english
