### ISSUE TITLE
Red button "Download complete" (but it's not)

### ISSUE THREAD

**Issue by pepa65** [ziahamza/webui-aria2#156]
A number of times the download (of a bittorrent) has stopped, with the red bar clearly not all the way full, and a red 'button' above the bar saying "Download Complete". If I press the rounded arrow button, the torrent will resume, and the bar will turn blue again.

The button should be labeled differently, like "Download incomplete". Even better would be an automatic restart in such cases.

**Comment by anthonyraymond** [comment]
Solved in a PR some time ago.
