### ISSUE TITLE
Multi server support

### ISSUE THREAD

**Issue by typcn** [ziahamza/webui-aria2#158]
Allow set multi server in config.
Download speed of some resources is very slow , we can choose raspberry pi or VPS to download , wait a later time and download it to local more faster.
(sorry for my bad english)

**Comment by kolonuk** [comment]
I use aria to download directly on my pi using nginx for my webserver.  I then access files later over samba from my windows laptop or android tablet...  Not sure what you are suggesting is any better than that...
