### ISSUE TITLE
Problem with downloaded file path !

### ISSUE THREAD

**Issue by yas9999** [ziahamza/webui-aria2#159]
Hello,
i have a problem, once i download the file & get the link to get my files it's always give 404 page not found !
i set download directory to /var/www/koko the files are there i guess there is a problem in some configuration
please check the image 
![aria2](https://cloud.githubusercontent.com/assets/5939771/8825188/1953ab1a-3075-11e5-98b1-6c0fb2fb602e.png)

**Comment by Aeryax** [comment]
Hi,

I don't have the time to check now, but in the settings there is a field named "base_url" (or similar). I think you need to put "http://52.17.173.76/aria2/koko/" in.

**Comment by yas9999** [comment]
Hello,
thank you so much :) it's work now

**Comment by kingdave** [comment]
I think there is a bug. When i set the directURL in configuration.js, it doesn't have any effect in UI or it does the same thing as @yas9999 is shows on the picture. Can someone take a look on it? Thanks.
BTW, I bypassed it by overwriting some methods in main.js and set the url there, but it is not an elegant solution.
