### ISSUE TITLE
Feature request: Able to choose jsonrpc path {socks;jsonrpc}  SSLApacheProxy support

### ISSUE THREAD

**Issue by lukasmrtvy** [ziahamza/webui-aria2#161]
Would be great if you could choose jsonrpc path. Problem is when you have mutliple jsonrpc services on same ssl enabled vhost.
For example KODI and Aria will not work until you edit some settings

1.)
To make ws://127.0.0.1:6800/jsonrpc listen on wss://127.0.0.1/aajsonrpc
Because there could be another jsonrpc service (for example KODI web interface).... 

```
 <Location /aajsonrpc>
    ProxyPass        ws://127.0.0.1:6800/jsonrpc  retry=0
    ProxyPassReverse ws://127.0.0.1:6800/jsonrpc
    SetEnv force-proxy-request-1.0 1
    SetEnv proxy-nokeepalive 1
 </Location>
```

2.)
Change all /jsonrpc occurrence in jsoncall.js and sockcall.js to /aajsonrpc

3.)
https://github.com/buffovich/webui-aria2/commit/b5624e279c224eaf099839d7637503eec8163bae

@ziahamza  Could you review your code to make it work in default? Thanks

**Comment by ziahamza** [comment]
IT should now show up in the Connection settings UI, and also configurable from configurations.js. Let me know if doesnt work or has any issues connecting with custom aria2 rpc endpoint

**Comment by muhahacz** [comment]
Seems that  path: '/myjsonrpc' in configurations.js doesnt work as default, webui always try to connect to jsonrpc...  
If i change it manualy in webui(connection settings), it works

Another question, Is possible to set jsonrpc connect timeout? Is it 10sec by default, right?

I have tried to change this variable, but seems it doenst work
.constant('$globalTimeout', 1000) 
Thanks

**Comment by muhahacz** [comment]
@ziahamza ?

**Comment by ziahamza** [comment]
I just pushed a new change into master ... which I think may fix the issue. Does it still happen with updated webui-aria2?

**Comment by muhahacz** [comment]
It is working now. Thanks

Another question, is possible to set connect to RPC timeout (from 10 seconds) ?

**Comment by ziahamza** [comment]
I just pushed a new version in master. hopefully it should fix the timeout issue :)
