### ISSUE TITLE
Show global down/up speed in title bar

### ISSUE THREAD

**Issue by vBm** [ziahamza/webui-aria2#162]
Would be nice if we'd have info about total (combined) down/up speed in title bar for example or even in sidebar.

Thanks in advance.

**Comment by ziahamza** [comment]
Hmm ... yeah, that can come handy too. Right now its separated I guess. But
some people do prefer them to be separate to know how things are going
especially with torrents as sometimes they can upload way more then
download. Would you find combined more useful?

**Comment by ziahamza** [comment]
Its a matter of taste I guess .... the fix should be minor to add this
change.

**Comment by vBm** [comment]
I'm thinking about having both to be honest. Combined is useful to see when i want to see if i'm maxing out my line or not :-) I'm using webui remotely most of the times.

**Comment by safiyat** [comment]
+1
I support vBm's suggestion. An overall up/down speed (along with total bytes/MBs transferred) in the titlebar and/or at any corner of the web page would be a good enhancement and handy for people who want to monitor their bandwidth.

**Comment by ziahamza** [comment]
Alrite, added basic support for upload/download speeds in the title bar. 
Open configuration.js and change the title pattern to: 'download speed: {download_speed} - upload speed: {upload_speed}'

**Comment by ziahamza** [comment]
by default, it shows active/waiting/stopped downloads. And in the main UI, we have a graph to monitor the download/upload speeds

**Comment by ziahamza** [comment]
Having total MB transferred is hard and tricky to do, as web ui is not always running, and it will loose track on how much is transferred.

**Comment by vBm** [comment]
I guess this one can be closed since we have exact info on index page thanks to 37127cccde4fde238b859c035ce6f6eaa8d1100f.

👍
