### ISSUE TITLE
How to add header property in webui?

### ISSUE THREAD

**Issue by ShaoXinSen** [ziahamza/webui-aria2#163]
In terminal, I download file use url like this:
`aria2  --header "cookie:xxx"  "http://adcdownload.apple.com/Developer_Tools/Xcode_7/Xcode_7.dmg"`

It's can download successful.

now, in the webui, I add this link to webui:
`http://adcdownload.apple.com/Developer_Tools/Xcode_7/Xcode_7.dmg --header="cookie:xxx"`

It's download failed.

So, how can i input the right url to download in webui ?

**Comment by famaridon** [comment]
Hi you can add header in "Advanced settings" -> "header" value is like it "Cookie: SID=xxx"

**Comment by ShaoXinSen** [comment]
thank you very much
