### ISSUE TITLE
Question about Quick Settings

### ISSUE THREAD

**Issue by sonokamome** [ziahamza/webui-aria2#164]
Is there a way to have the settings stay permanent in some file? I tried to figure it out on the config.js file but I can't find the place where to enter the values I want to enter. 

Thanks in advance!

**Comment by xeddo** [comment]
I had to manually change the connection settings in configuration.js, because the UI did not save them permanently.
The Quick Access Settings checkboxes don't work at all for me and can only be changed manually, by editing configuration.js.

**Comment by ziahamza** [comment]
The ui can not access files, its just a webpage and can only do limited
stuff. So normal download settings will be saved by aria2 but for webui
settings its hard to store prrmanant... maybe cookies

**Comment by xeddo** [comment]
ok, this makes sense.
I just thought it was some kind of bug, because there is a "save"-settings button :D

**Comment by ziahamza** [comment]
Yeah ... the wording is a bit bad there :P

**Comment by misacek007** [comment]
I have correct settings in configuration.js but when aria cannot be connected at first (is not running) I always end up with some kind of default which I need to manually change. Is this expected?

**Comment by ziahamza** [comment]
Yea, if it can't connect then it falls back to the default configuration
and tries that too. if it all fail then it quits. The auto connect feature
is just there as a convenience

**Comment by igitur** [comment]
So does that mean even my list of downloads is discarded when I restart the `aria2c` backend and reload the browser?
