### ISSUE TITLE
Can't download to nfs share drive directory

### ISSUE THREAD

**Issue by wsian** [ziahamza/webui-aria2#174]
I've been trying to set download directory to a NAS shared drive (using nfs).
I can write and delete files in the shared drive after mounting.
However when using webui-aria2 and set dir to this shared drive, it always display "download was successful" but file is with 0 bytes.
Has anyone try this before?

**Comment by Jonathan34** [comment]
it says "download was successful" in a red background which means not successful obviously.
It is unlikely that it is releated to webui-aria2 but more with the aria2c client.

Check /var/log/aria2.log or wherever the logs are. they usually contain information on what is going wrong (permission, file allocation failed...)

**Comment by ziahamza** [comment]
Yeah, probably an issue with aria2 ... Webui should be sending downloading request go aria2 properly

**Comment by lilarcor** [comment]
you can try to set file-allocation=none in you aria2.conf

**Comment by John-Constantine** [comment]
@lilarcor Thanks.It work.

**Comment by Daopr** [comment]
Thanks， it works. But it may cause more hurt to disk?

**Comment by ChiaSang** [comment]
@lilarcor Thinks ！ it works！！！

**Comment by scutxd** [comment]
> @lilarcor Thinks ！ it works！！！

Can you share your .conf file? What is the --dir para?

**Comment by lilarcor** [comment]
I don’t use it more and I didn’t backup the conf.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by scutxd** [comment]
OK, thanks.
