### ISSUE TITLE
cannot download video

### ISSUE THREAD

**Issue by yagami1234** [ziahamza/webui-aria2#180]
i have some problem with aria,i cannot download video except from youtube
for example video like this

https://r1---sn-npo7zn7k.googlevideo.com/videoplayback?id=372774fb703092c2&itag=18&source=webdrive&requiressl=yes&mm=30&mn=sn-npo7zn7k&ms=nxu&mv=m&nh=IgpwcjAxLnNpbjAzKgkxMjcuMC4wLjE&pl=24&mime=video/mp4&lmt=1454095398599451&mt=1454234865&ip=112.215.64.121&ipbits=8&expire=1454263743&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mn,ms,mv,nh,pl,mime,lmt&signature=7D98B18C52476890925623E160A76417E7F79D41.27E269E5112B64E079860FB64AAD829C4FB727EA&key=ck2

i took it from kissanime btw
which setting that i have to change? because so far i didn't change anything 
and because i'm still newbie i just try to change setting by random but so far no result,still error
or this is a bug?

**Comment by kolonuk** [comment]
That's not a video - if you put that link into a browser, it doesn't download.  Do you have the original web page?

**Comment by yagami1234** [comment]
Yes that link doesn't direct download when you open it from several browser(except opera mini on android),but when you put it on download manager like IDM in windows or ADM in android it works
And yesterday i got some suggestion to put quotes between links,but it's only work when i download it from PuTTY
Since webui aria doesn't show why i can't download it,i can't figure it out how to fix it (._. )
That video link only work for a day,by the way
If you want,i can give you another link :D

**Comment by yagami1234** [comment]
Yes that link doesn't direct download when you open it from several browser(except opera mini on android),but when you put it on download manager like IDM in windows or ADM in android it works
And yesterday i got some suggestion to put quotes between links,but it's only work when i download it from PuTTY
Since webui aria doesn't show why i can't download it,i can't figure it out how to fix it (._. )
That video link only work for a day,by the way
If you want,i can give you another link :D

**Comment by yagami1234** [comment]
Yes that link doesn't direct download when you open it from several browser(except opera mini on android),but when you put it on download manager like IDM in windows or ADM in android it works
And yesterday i got some suggestion to put quotes between links,but it's only work when i download it from PuTTY
Since webui aria doesn't show why i can't download it,i can't figure it out how to fix it (._. )
That video link only work for a day,by the way
If you want,i can give you another link :D

**Comment by yagami1234** [comment]
Yes that link doesn't direct download when you open it from several browser(except opera mini on android),but when you put it on download manager like IDM in windows or ADM in android it works
And yesterday i got some suggestion to put quotes between links,but it's only work when i download it from PuTTY
Since webui aria doesn't show why i can't download it,i can't figure it out how to fix it (._. )
That video link only work for a day,by the way
If you want,i can give you another link :D

**Comment by yagami1234** [comment]
Yes that link doesn't direct download when you open it from several browser(except opera mini on android),but when you put it on download manager like IDM in windows or ADM in android it works
And yesterday i got some suggestion to put quotes between links,but it's only work when i download it from PuTTY
Since webui aria doesn't show why i can't download it,i can't figure it out how to fix it (._. )
That video link only work for a day,by the way
If you want,i can give you another link :D
