### ISSUE TITLE
Request: Select multiple path for new download

### ISSUE THREAD

**Issue by crottolo** [ziahamza/webui-aria2#182]
Hello, I have new request for this gui: i would combobox for seletch different path, because if I have different path, I can select the folder:
Eg: Multimedia/video, Multimedia/pictures, ISO/linux, ISO/windows, software/win, software/apple...

Thanks in advance

**Comment by ziahamza** [comment]
hmm ... that would be super helpful actually. Let me push that when I get time

**Comment by kschinkel** [comment]
I was actually wondering if a directory browser was going to be implemented? What crottolo suggested would be helpful also, but basically anything other then typing the path manually :). For those of us who have multiple paths we download to.
