### ISSUE TITLE
file downloaded cannot be removed via webui

### ISSUE THREAD

**Issue by elunatix** [ziahamza/webui-aria2#186]
i have no problem to remove the files from the webui list. However, the actual downloaded files are still on the server. the files were downloaded using torrent magnet link. how to fix this?

**Comment by Hoshiyuu** [comment]
I have the same issue running Aria2c of a Digital Ocean hosted ubuntu instance.

**Comment by Twilight** [comment]
as of my understanding, that "remove" options means remove download tasks, not files, and aria2c RPC API doesn't provide such functionality.

**Comment by ziahamza** [comment]
Yeah, WebUI can at max control aria2 but not the actual files downloaded by aria2

**Comment by Suncatcher** [comment]
> Yeah, WebUI can at max control aria2 but not the actual files downloaded by aria2

Why? Doesn't Aria2 have API for accessing downloaded files?

**Comment by Jimmy-Z** [comment]
No it doesn't, https://github.com/aria2/aria2/issues/728
