### ISSUE TITLE
Default Language

### ISSUE THREAD

**Issue by beautifulape** [ziahamza/webui-aria2#187]
Hi, it looks like the web page cannot remember my language setting by using the switch. 

I'm wondering if there is a way to force the page to load a chosen language?

**Comment by jiajunhuang** [comment]
+1

**Comment by Xuanwo** [comment]
Maybe you can set it in configure.js

**Comment by dawidd6** [comment]
+1

**Comment by cyc1610** [comment]
Hi ,

You can modify init.js

32 lines

.translations('en_US', translations.en_US)

'en_US' is related to your system language

I use traditional Chinese, so to change

.translations ( 'zh_TW', translations.zh_CN)

![default](https://cloud.githubusercontent.com/assets/23048134/19807943/fe21255e-9d54-11e6-8e33-0839e0331e7b.png)

**Comment by 540369718** [comment]
Hi, @cyc1610 I just modify init.js 
like this:
![Uploading 屏幕快照 2017-03-21 下午1.40.24.png…]()
but didn't work.

**Comment by 5night** [comment]
<img width="433" alt="screen shot 2017-03-21 at 6 18 26 pm" src="https://cloud.githubusercontent.com/assets/2508769/24142962/1f4328d4-0e63-11e7-8cb5-89db9d192e6a.png">

add ".fallbackLanguage("zh_CN");" in init.js fix this

**Comment by 540369718** [comment]
Hi, @5night 
I add this, but WebUI is blank.
<img width="1227" alt="2017-03-21 7 11 09" src="https://cloud.githubusercontent.com/assets/8408547/24145015/683a98ea-0e6a-11e7-92dc-2d053e50bbf1.png">

**Comment by 5night** [comment]
@540369718 remove the ";" after determinePreferredLanguage()
就是说去掉图中45行的那个分号。
