### ISSUE TITLE
Uploaded amount

### ISSUE THREAD

**Issue by Spider-Mann** [ziahamza/webui-aria2#188]
The uploaded amount in the detailed view of an torrent is not updated.

**Comment by Lyken17** [comment]
I have the same issue 
<img width="905" alt="screenshot 2016-07-18 14 23 01" src="https://cloud.githubusercontent.com/assets/7783214/16930918/2a3a3656-4cf3-11e6-9e77-f81f4a2b2520.png">

**Comment by carlnorum** [comment]
I think I just fixed this one: https://github.com/ziahamza/webui-aria2/issues/310

**Comment by carlnorum** [comment]
https://github.com/ziahamza/webui-aria2/pull/309
