### ISSUE TITLE
Why config in webui is different from my local config?

### ISSUE THREAD

**Issue by cajsaiko** [ziahamza/webui-aria2#190]
For example, in my local config file I have set split to 10, but when I add a task and click the advanced settings I found spilt is 5, so which one take effect when it is downloading?

**Comment by ziahamza** [comment]
That should be weird ... how do you change the split in the config file? Perhaps it not being properly set in config ...

**Comment by cajsaiko** [comment]
I write like `split=10`, it seems all configs just use default value, but I **find the dir config is right**, I don't know where is wrong, my config file like this [config](https://github.com/hzamani/aria2web/blob/master/config/aria2.conf).

**Comment by cajsaiko** [comment]
I find that global setting is 10, but when I add a new task why the split value is 5? and which one is preferred?

**Comment by Twilight** [comment]
I think the new task value is cached by webui

per task setting overrule global setting.
