### ISSUE TITLE
Uri window features

### ISSUE THREAD

**Issue by melona380** [ziahamza/webui-aria2#194]
I want to change the fields in the add url page.
I want to add a textbox for a file name instead of in the url. And I want to add radio buttons. Below the dir textbox and have pre specified download locations...

The main question here is: where is the code used to build the add url window.

It looks like on the main page it looks through pre set settings that defines what to put. Where are these settings?

**Comment by ziahamza** [comment]
The model dialog box for add urls is opened here: https://github.com/ziahamza/webui-aria2/blob/master/js/ctrls/modal.js#L51

The html of the model lives here: https://github.com/ziahamza/webui-aria2/blob/master/index.html#L686

the user defined settings live here: https://github.com/ziahamza/webui-aria2/blob/master/configuration.js

And predefined settings which are set by default live here: https://github.com/ziahamza/webui-aria2/blob/master/js/services/settings/settings.js

Let me know if its still confusing or if you have any other question :)

**Comment by melona380** [comment]
Ok, I have found these. But what has me confused is at:
[https://github.com/ziahamza/webui-aria2/blob/master/index.html#L712]
It looks like it loops through all the items that end up on that form. I tried to add a few radio buttons by:

       
```
  <div class="form-horizontal modal-advanced-options">
            <div class="form-group" ng-repeat="(name, set) in getUris.settings">
             <label class="col-sm-3 control-label">{{name}}</label>

              <div class="col-sm-9 controls">
                <select class="form-control" ng-show="set.options.length" ng-options="opt for opt in set.options" ng-model="set.val">
                </select>
                <input ng-show="!set.options.length" type="text" class="form-control input-xxlarge modal-form-input-verylarge" ng-model="set.val"/>
				  <input type="radio" name="dir" value="movies"> Movies<br>
					  <input type="radio" name="dir" value="tv"> TV<br>
					  <input type="radio" name="dir" value="zip"> Extract(.zip)<br>
					  <input type="radio" name="dir" value="samtv"> Sam TV<br>
					  <input type="radio" name="dir" value="cat"> CAT<br>
					                
              </div>
              <br />
            </div>
          </div>
```

However This is the result:
![image](https://cloud.githubusercontent.com/assets/11069376/13726335/dc1d1962-e888-11e5-8475-cfd66ff8b8a3.png)

What i need to find is exactly where the cod for the **dir** textbox is being made and modify where that code is before it is looped onto index.html.

**Comment by ziahamza** [comment]
So all the different options live in this object:
https://github.com/ziahamza/webui-aria2/blob/master/js/ctrls/modal.js#L41

initially its empty, but it is filled from pre-saved default settings here:
https://github.com/ziahamza/webui-aria2/blob/master/js/ctrls/modal.js#L46

for adding custom form fields, you can add/change a specific setting right at line 50 of js/ctrls/modal.js
e.g. to change the way dir is displayed, add the following code into line 50:
```self.settings['dir'] = { vals: ['/home/Downloads', '/home/Desktop'], desc: "The directories to store the file"}```

**Comment by melona380** [comment]
Hi, I added
`self.settings['dir'] = { vals: ['/home/Downloads', '/home/Desktop'], desc: "The directories to store the file"};`
to line 50 but nothing changed. Maybe it would be easier if I could change the dir input type to the combobox like, the pause input type. Then fill in the values I want in that combo box... I am still learning js. Thus how could one accomplish this?

**Comment by ziahamza** [comment]
Sorry, the object contains 3 items: 

- desc: which is the description of the option
- val: which is the initial selected value of the option (I wrongly told you vals)
- options: which will limit the values to certain options, like a combo box

so the line of code you should add is:
```self.settings['dir'] = { val: '', desc: 'The location of the downloaded file', options: ['/home/Downloads', 'home/Desktop'] };```

**Comment by ziahamza** [comment]
I added the line and I got this:
<img width="599" alt="screen shot 2016-03-12 at 6 00 52 pm" src="https://cloud.githubusercontent.com/assets/206640/13726445/6e7dd2c2-e87c-11e5-824b-cf21fcb5bd64.png">

**Comment by melona380** [comment]
THANK YOU SOOOO MUCH!!! That worked, I just have one final question: Instead of typing `-out=file.txt ` how could a text box be added to enter a file name?

**Comment by ziahamza** [comment]
Thats going to be much harder, as the box accepts multiple links to multiple files, so one file name box wont be enough. There have to dynamic depending on how many urls are entered in the url box... you could add another modal which only downloads one single file, and then have a file name box there but you will need to add some code for that

**Comment by melona380** [comment]
Ok, I will look into that. Maybe in a future release **HINT HINT** Thank you.

**Comment by ziahamza** [comment]
you are welcome :)
