### ISSUE TITLE
Add RPC login to config while Web hosted

### ISSUE THREAD

**Issue by melona380** [ziahamza/webui-aria2#195]
I want to add the rpc credentials automatically. You can do this in:
[https://github.com/ziahamza/webui-aria2/blob/master/configuration.js#L11](url)
However if you are Web facing you can visit example.com/configuration.js  and see the rpc credentials in plan text! Due to how I have ssl setup the webui and rpc are web facing.** How can I add the same credentials without it being accessible over the internet?**

**Comment by ziahamza** [comment]
There is no way to keep the credentials secret if they become part of code ... so its most recommended to either put webui behind http authentication (using something like apache or nginx) and then store the aria2 secret in the configuration file.

**Comment by melona380** [comment]
Ok, Thank you... I fixed it by setting apache auth
