### ISSUE TITLE
Language Display issue on chrome 49.0.2623.87 (64-bit)

### ISSUE THREAD

**Issue by maintiendrai** [ziahamza/webui-aria2#199]
![issue](https://cloud.githubusercontent.com/assets/393540/13904717/4931bdb2-eee4-11e5-990c-d90713b9f960.png)

**Comment by ziahamza** [comment]
Seems like the javascript is not running atall .... have you tried refreshing the page? or trying to use a different browser?

**Comment by pietrondo** [comment]
same problem.. chrome and firefox
![selezione_293](https://cloud.githubusercontent.com/assets/6080662/15691548/c0115ad6-2789-11e6-8543-32c0017ef050.png)

**Comment by roo79x** [comment]
hi all I'm having this same issue, git cloned into /var/www/html/webui-aria2/
I'm running ubuntu server 16.04 doesn't matter what browser I used the tutorial from here https://jlnostr.de/en/blog/aria2-raspberrypi. and when I try to connect to aria2 on the server through http://ziahamza.github.io/webui-aria2/ I cant connect. my /home/roo79x/.aria2/aria2.config looks like 

continue
daemon=true
dir=/mnt/disk1/Downloads
file-allocation=falloc
log-level=warn
max-connection-per-server=4
max-concurrent-downloads=3
max-overall-download-limit=2M
min-split-size=5M
enable-http-pipelining=true

enable-rpc=true
rpc-listen-all=true
rpc-secret=exampletoken

I am very new to aria2 and this webui but they are exactly what I want I'm sorry to be a pain to those of you more knowledgeable. Any help would be great

Thanks for your time
Roo79x

**Comment by ochbob** [comment]
Same problem here.

**Comment by Amarok73** [comment]
+1
