### ISSUE TITLE
Associate .torrent file with Aria2webui

### ISSUE THREAD

**Issue by pingshunhuangalex** [ziahamza/webui-aria2#200]
Hi ziahamza

I used a local version of your aria2ui, and it works great so far. Just one thing in daily use, torrent file is always a pain as their download paths are usually masked, i.e. the url won't lead me directly to the torrent file, it directs me to another link which downloads the torrent. Therefore, sending the url directly to aria2 won't work, I have to use chrome to download the torrent file and then add it into aria2ui.

So my question is:
Is there a way to associate .torrent file with Aria2ui, i.e. when I open (double click) the torrent file, it can open the task window in Aria2ui, just like when I click add torrent and select the torrent file. Thanks.

**Comment by olsonbg** [comment]
You can try using a browser extension that is designed to work with aria2. I use the [Aria2c Integration](https://chrome.google.com/webstore/detail/aria2c-integration/edcakfpjaobkpdfpicldlccdffkhpbfk?utm_source=chrome-app-launcher-info-dialog) extension for chrome, it works great for me. I wouldn't be surprised if there are more extensions than just that one which you could choose from, so pick the one that works the best for you.
