### ISSUE TITLE
A button to open download directory

### ISSUE THREAD

**Issue by pingshunhuangalex** [ziahamza/webui-aria2#208]
Hi ziahamza
I think we need a button (one of the label showing download path) to open the download directory folder, don't you think?

Also, has the torrent list display been fixed? Thanks.

**Comment by ziahamza** [comment]
Does the torrent list display bug have an issue on github? 

This should be possible and quite handy if the webserver already supports displaying directors of the download folder ... without it webui wont be able to display the folder of the download directory  I guess

**Comment by pingshunhuangalex** [comment]
Thanks for the reply.

Now I figured I can't find the torrent list function anymore. Is it removed?

I'll leave the directory fix to you, just a suggestion, and I actually have no idea what you are talking about...
