### ISSUE TITLE
Could not connect to the aria2 RPC server

### ISSUE THREAD

**Issue by snak31** [ziahamza/webui-aria2#209]
Hey guys, I have a router and i install aria2 and the webui-aria2, i lauch the command aria2c --enable-rpc --rpc-listen-all and i show [NOTICE] IPv4 RPC : Listening on TCP port 6500, i open this port on my router for a acces on webui on WAN but i have : Oh Snap! Could not connect to the aria2 RPC server. Will retry in 10 secs. You might want to check the connection settings by going to Settings > Connection Settings.

Please help me

PS : Sorry for my bad english i'm a french student ^^'

**Comment by ziahamza** [comment]
You would need to put the IP address of your router in the connection settings. Just starting aria2 is not enough to use web-ui. Are aria2 and webui hosted on the same IP?
