### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by jdarias** [ziahamza/webui-aria2#213]
I´m interested in translating to spanish, but i´m new to github.
What should I do?

**Comment by jdarias** [comment]
So far I forked the project and did what it said in the translation template.

**Comment by ziahamza** [comment]
so then you can send a pull request. Then I can make your changes live to everyone! :)

**Comment by ziahamza** [comment]
IT should be pretty easy. There is a pull request button in your fork repository link (https://github.com/jdarias/webui-aria2). Click that. and then click create a pull request. I can then look at the code changes, and then put them in the main project here. Then everyone can see the spanish translation

**Comment by jdarias** [comment]
Pull request sent :)
