### ISSUE TITLE
Alert strings that need translation.

### ISSUE THREAD

**Issue by jdarias** [ziahamza/webui-aria2#217]
The alerts the app gives while connecting need translation. How can this be done? I tried using {{ string | translate }} but this only works in html :P hehe

Here are the strings in question:

`The last connection attempt was unsuccessful. Trying another configuration`

`<strong>Oh Snap!</strong> Could not connect to the aria2 RPC server. Will retry in 10 secs. You might want to check the connection settings by going to Settings > Connection Settings`

`Successfully connected to Aria2 through its remote RPC …`

`Successfully connected to Aria2 through remote RPC, however the connection is still insecure. For complete security try adding an authorization secret token while starting Aria2 (through the flag --rpc-secret)`

`Trying to connect to aria2 using the new connection configuration`

**Comment by ziahamza** [comment]
@jdarias I have added the new alert strings in the translate template. They should translate correctly when translation is available.

**Comment by jdarias** [comment]
ok. new pull request sent.
