### ISSUE TITLE
Forking for modifications

### ISSUE THREAD

**Issue by piyushkmr** [ziahamza/webui-aria2#220]
Hey, I liked your aria2 webui very much.
I wanted to do some changes to this awesome ui. Also I would like to present it in an installer format via apt-get and/or via install.sh.

So, I want to know "**Can I create a fork to your respository and modify it as per I need and publish it to ubuntu/ other linux as installer, under my name and keeping your name and link as original author?**"

I cannot create modifications into your current project as there will be huge changes in UI.

**Comment by ziahamza** [comment]
Yeah, that is completely fine by me. Would appreciate if you attributed it back :)

**Comment by RoToRx88** [comment]
Hi @piyushkmr, I'm also looking to change the UI to have more material design style ! Can you update here some news when you will update it and maybe a link to your fork ? :)
