### ISSUE TITLE
[Feature] Missing a way to send URL from browser contextual menu

### ISSUE THREAD

**Issue by BoringUserWhoCantCode** [ziahamza/webui-aria2#221]
Needs a way that adds a contextual option that appears by right clicking a link to send it to the download queue to be shown in the WebUI.

**Comment by gbcox** [comment]
Not sure what browser you are using, but for:
chrome you can use:
Aria2c Intergration - https://goo.gl/eQ7OYu
Firefox:
Sent to aria2 - https://goo.gl/13JnVP

I don't believe that browser integration is the aim of this project... but rather to create a web interface to be able to easily control the server.  This project works with any browser, but creation of an option in a contextual menu is browser specific - and there are already extensions that do that.

**Comment by ziahamza** [comment]
Complete agree with you @gbcox ... The aim for this project would not include browser specific stuff

**Comment by BoringUserWhoCantCode** [comment]
Thanks very much for your work indeed. Yes, you're both right. And thanks for the extension, @gbcox; works perfect.
