### ISSUE TITLE
Is it possible to download the downloaded files as a single zip?

### ISSUE THREAD

**Issue by YamiOdymel** [ziahamza/webui-aria2#223]
Like below (_Sorry for the blur effect_):

![2016-05-16 1 45 55](https://cloud.githubusercontent.com/assets/7308718/15275806/0f75bf38-1b08-11e6-8fbb-709d783e430c.png)

It's a challenge for me to download each downloaded file,

don't know if there's any chance to add a `Download all` button or

this is not the thing that `web-ui` can do?

**Comment by ziahamza** [comment]
Its something that web-ui may not be able to do unfortunately :/

It has to be implemented in any webserver that you run on the server to download a folder by zip
