### ISSUE TITLE
Access aria2 remotely

### ISSUE THREAD

**Issue by n00b12345** [ziahamza/webui-aria2#225]
While accessing Aria2 web UI remotely, the currently downloading files don't show up. The login works fine but it starts with an empty download slot. Is this by design?

**Comment by ziahamza** [comment]
hmm ... this is super weird. It should show all the pending downloads from aria2. Are the downloads running in the background?

**Comment by n00b12345** [comment]
Yes. As in, I have Aria2 installed on a raspberry pi. Now I access WebUI and initiate downloads from the browser of another computer. So, nothing is running in the foreground so to speak. 

When I move to another network, I a clear WebUI page with no ongoing downloads.

**Comment by ziahamza** [comment]
that sounds like a clear bug. Are you using the same authentication details and the same security token @n00b12345 ?

**Comment by n00b12345** [comment]
@ziahamza I'm using the same authentication (username & password) details. (I don't use a security token, call me extremely lazy)

**Comment by ziahamza** [comment]
on the same network, what if you use 2 different browsers to see the webui. Do you see consistent results?

**Comment by n00b12345** [comment]
Yes on the same network, regardless of the browser I use, I get consistent results.

**Comment by ziahamza** [comment]
This seems to be an aria2 bug @n00b12345 , as webui will not change depending on which network it is running under. ... perhaps report it here: https://github.com/aria2/aria2

**Comment by n00b12345** [comment]
Thanks. A small correction @ziahamza. I tried accessing it again from a data connection this time. I was assuming thus far that my browser was automatically providing username and password to Aria Web UI when accessing remotely. I was wrong. I'm not being asked username and password by Web UI when accessing remotely. Terribly sorry about the confusion.

**Comment by n00b12345** [comment]
@ziahamza Made a rookie error. Hadn't forwarded port 6800. Terribly sorry. Everything works fine now. Thanks for the help!
