### ISSUE TITLE
Cannot connect to RPC via nginx

### ISSUE THREAD

**Issue by heartsaver1859** [ziahamza/webui-aria2#230]
**My config:**

**nginx aria.conf:**
server {
  listen 80;
  server_name aria.first_level_domain;
  # enforce https
  return 301 https://aria.first_level_domain;
  }

server {
  listen 443 ssl;
  server_name aria.first_level_domain;
  ssl_certificate /etc/letsencrypt/live/aria.first_level_domain/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/aria.first_level_domain/privkey.pem;
  ssl_session_timeout 1d;
  ssl_session_cache shared:SSL:50m;

  ssl_dhparam /etc/ssl/certs/dhparam.pem;

  ssl_protocols TLSv1.1 TLSv1.2;
  ssl_ciphers my_ciphers;
  ssl_prefer_server_ciphers on;

  ssl_stapling on;
  ssl_stapling_verify on;
  ssl_trusted_certificate /etc/letsencrypt/live/aria.first_level_domain/chain.pem;

  root /var/www/aria2;
}

**Aria2c conf**

log=/var/log/aria2.log
log-level=info
dir=/data/downloads
#rpc-secret=my-secret
disable-ipv6=true
rpc-listen-all=true
rpc-listen-port=8599
enable-rpc=true

**netstat -pnlt | grep ':8599'**
tcp        0      0 0.0.0.0:8599            0.0.0.0:*               LISTEN      3061/aria2c

**aria2-webui**

  host: 'localhost',
  path: '/jsonrpc',
  port: 8599,
  encrypt: false,
  auth: {
  token: 'my-secret'
  },

**XML-RPC tool**
http://my.ip:8599/rpc

The tool can connect to my aria2c but webui can't estabish a connection i tried diferent settings. Without any success... i tried to type in my IP or my subdomain or as you can see localhost. 

But i only can connect to my ip with /rpc and not /jsonrpc

**Comment by bebehei** [comment]
https://xkcd.com/979/

**Comment by bebehei** [comment]
Well, the solution to my problem was, that you simply had to add another location (`/jsonrpc` by default), which nginx should proxy directly to aria2c's RPC command. Otherwise if you just connect to the website, you'll get only shown the html, but not the data.

So a matching config would be:

```
        location /jsonrpc {
                proxy_pass         http://<aria2c listening ip>:6800;
                proxy_set_header   Host $host;
                proxy_set_header   X-Real-IP $remote_addr;
                proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header   X-Forwarded-Host $server_name;
        }
```

Probably you don't need the `proxy_set_header` directives, but I'll just use my aria2 box for a few days.
