### ISSUE TITLE
Secret token from configuration.js fails

### ISSUE THREAD

**Issue by johnlane** [ziahamza/webui-aria2#233]
I am trying to use a secret token in `configuration.js`, like this:

```
token: 'secret'
```

but it fails. However, if I add the word `secret` into the Settings screen then it works fine. I am not sure what I am doing wrong. I have tried both `secret` and `$secret$` both unsucessfully.

I have added an `alert(currentToken);` at `js/services/rpc/rpc.js:90` and it displays the correct `secret` value.

It starts working as soon as I type the word `secret` into the _Enter the secret token (optional)_ box, even before I press the _save_ button, but it doesn't work when relying on the value in `configuration.js`.

I can't see what I am doing wrong; perhaps I have hit a bug?

(I have latest checkout a4b1e954)

**Comment by dopeghoti** [comment]
When you start `aria2c`, are you using the same secret in the `--rpc-secret` switch?

**Comment by anthonyraymond** [comment]
do NOT put your token in `configuration.js`, the file can be accesed by anyone by tipyng the url in the browser, this is extremely unsafe.

**Comment by no1xsyzy** [comment]
same as #347 just clear the cookies.
