### ISSUE TITLE
on-download-complete waits until seeding has finished

### ISSUE THREAD

**Issue by spot1701** [ziahamza/webui-aria2#234]
I use "on-download-complete" to call a script to notify me that a download has finished.
But when downloading a torrent "on-download-complete" isn't fired until the torrent has finished seeding, not when the download has completed.

**Comment by olsonbg** [comment]
This is correct behavior for "on-download-complete", try [on-bt-download-complete](https://aria2.github.io/manual/en/html/aria2c.html?highlight=on-bt-download-complete#cmdoption--on-bt-download-complete) instead.

**Comment by spot1701** [comment]
Perfect. Thanks.
