### ISSUE TITLE
webui-aria2 and aria2 configuration

### ISSUE THREAD

**Issue by chrisandrewcl** [ziahamza/webui-aria2#239]
First of all: congrats, this gui is really the best and hottest!

... sorry if it is already a known "issue" but I can't find all the answers for this questions.
I don't quite get how "Global Settings" works in webui-aria2: I don't think the web app has permission to access local files, and the values don't seem to affect aria2 behaviour. They aren't even persisted!

For me neither the simple "quick setting" toggles seems to affect the webui front-page.

I am missing something here?

Is it possible to:
- Persist settings in cookies or local web storage? or
- Export settings in "aria2.conf" format?

**Comment by Suncatcher** [comment]
BTW, how is webui-aria2 settings are persisted now? When I open URL again after a short time, my download list is opened as I left it.
Does it use cookies?
