### ISSUE TITLE
RPC secret token isn't working as expected

### ISSUE THREAD

**Issue by n00b12345** [ziahamza/webui-aria2#253]
This is what I'm using to launch Aria

`aria2c --enable-rpc --rpc-listen-all --rpc-secret`

The rest of the settings lie in a config file which specifies download location and 

`rpc-secret=token`

I've also added the token as token: 'token' in the configuration.js file. 

However, when I launch the web interface, I still get a cannot connect error. 

If possible, kindly help. 

(I've been using WebUI for many months now and the latest update probably was what caused the problem. I was previously using user and password)

**Comment by ziahamza** [comment]
this is weird if its recent. @n00b12345 Do you host aria2c & webUI from the same IP? And also, have you tried manually setting the connection details in the connection dialog in the app?

**Comment by n00b12345** [comment]
@ziahamza yes. Both are hosted on the same IP. A raspberry Pi. I've tried manually setting the connection. 

A small query, http://ipaddress:6800 opens a blank page whereas http://ipadress/aria obviously opens the WebUI but gives me the can't connect errors. Does this tell you anything?

Thanks for helping btw.

**Comment by ziahamza** [comment]
@n00b12345 one solution, would be to put `http://ipaddress` as the link to connect from the connection dialog within the app, to see if it works.

**Comment by n00b12345** [comment]
@ziahamza FIXED! 

This is dumb but I'll still explain what went wrong. Hopefully people in my situation can fix it.

I a running Aria on a Raspberry Pi. Recently I turned off the GUI but completely forgot to add Aria to /etc/rc.local. So, of course the WebUI couldn't connect :) Terribly sorry about this.
