### ISSUE TITLE
Notification when download is finished

### ISSUE THREAD

**Issue by pingshunhuangalex** [ziahamza/webui-aria2#256]
Not sure if this function is related to this project, but is it possible to add a notification feature when a task finished downloading?

I found parameters like ```--on-bt-download-complete, --on-download-complete, --on-download-error, --on-download-pause, --on-download-start, --on-download-stop``` which should allow aria2 to trigger some script as notification, but I'm not sure how to achieve it... Am I in the right direction?

**Comment by logicsys** [comment]
More of an aria2 question , but yeah, those parameters accept a command string, for example:

--on-download-complete=<COMMAND>

    Set the command to be executed after download completed. See See Event Hook for more details about COMMAND. See also --on-download-stop option. Possible Values: /path/to/command

So if you just wanted to receive an email when a download completes, you could set --on-download-complete="mail -s \"Download Complete\" myemail@mail.com | echo \"Download Complete at:\n\t$3\"

Replace myemail@mail.com with your email, $3 in the message body is the argument that contains the filename of the completed download.

Full manual is at: https://aria2.github.io/manual/en/html/aria2c.html

**Comment by Ritiek** [comment]
@pingshunhuangalex 
Hi, i had similar issue in the past. You can send notifications to your phone but they cost you. Somehow, I found a free app on playstore and automated it using python.
You can find the app here https://play.google.com/store/apps/details?id=com.soy.remotealert (all credits to its author) and code to run it here https://github.com/Ritiek/Remotealert.
You can customize the script according to you and add it to --on-download-complete=

Notifications take a few seconds before reaching your phone but better still than nothing.
Hopefully aria2 developers would develop a much better alternate to this..
