### ISSUE TITLE
Accessing web interface using Weaved on Raspberry Pi

### ISSUE THREAD

**Issue by Ritiek** [ziahamza/webui-aria2#267]
Thanks for developing this awesome web interface.
I am using it on raspberry pi 2.

It works fine locally but if i try to access it remotely from weaved it would not connect to the aria2 port (it would show the web interface but is unable to connect to aria2, popping out an error in red bubble).

Has someone tried connecting it via weaved successfully?

**Comment by ziahamza** [comment]
hmm ... @Ritiek so it works when you directly connect to Rasberry pi (without weaved)? Maybe the aria2 RPC port is being blocked.

**Comment by Ritiek** [comment]
@ziahamza Yes, it works fine if i connect directly to pi but not when connecting with weaved. It pops out the red message 'unable to connect aria2 rpc port' when i open the web interface using weaved..

why is it unable to connect to aria2 rpc port when using weaved?

**Comment by ziahamza** [comment]
it could be that weaved is blocking the connection to aria2 RPC from the webui. The Aria2 RPC runs on port `6800` and webui connects to that url. check if: http://url_for_weaved:6800 returns a response

**Comment by vanbwodonk** [comment]
I can connect webui with hamachi + apache2. First install apache then clone aria-webui inside /var/www/. Find /etc/apache2/sites-available/000.default.conf, then i changed the root directory from /var/www/html to /var/www

**Comment by Ritiek** [comment]
Thanks for trying to help but it was something different in my case..

If connecting via weaved gives an https page so we have to change it back to http manually (if you get https page an alternate will be to select 'this app uses a web browser' when setting up weaved to no).

Also, we have to manually enter the local address (not just localhost but local ip that can be known by running ifconfig in terminal) and port of aria2 server in Settings > Connection Settings in webui (in my case, local ip is 192.168.82.103 and port is 6800).

Then it connects successfully.

So is it possible to change the default ip address and port of aria2 server in webui (instead of localhost and 6800) so we do not have to do it ourselves everytime we open webui using weaved?

**Comment by Ritiek** [comment]
<b>EDIT:</b>

Something is really weird idk. Tried running the web interface using weaved from outside my house (with settings i posted above) and it didn't worked and gave an error 'could not connect to aria2 server. trying again in 10s' and then later when i tried connecting it again using weaved inside my home network it works fine (with same settings posted above)..

I think its because when i feed the ip of my pi in connection settings in webui it works because that ip actually exists on my local network and works fine but not when i connect it from some other network.

BTW, i do not think this related but i use lighttpd and have files for for webui in `/etc/www/html/aria/index.html` and can open it on my local network using my pi's ip `192.168.82.103/aria/index.html`.

Error when running weaved from outside home network:
<img src="https://cloud.githubusercontent.com/assets/20314742/19628258/77f2246e-9977-11e6-9231-9810741f05dc.png" width="400">

Any ideas?

**Comment by vanbwodonk** [comment]
@Ritiek are you using apache? I don't know how weaved works, it seems tunneled because had a port to connect. Maybe if tunneled it needs http(s)secure connection. Thats maybe why your connection dropped. You must setting your router,
[http://readwrite.com/2014/06/27/raspberry-pi-web-server-website-hosting/](url)
Hamachi is something different, hamachi had virtual physical connection called ham0 so it's just like local connection. Better than weaved if we have 5 clients. I still using weaved for Android ssh.
Sorry for my bad english.

![webui](https://cloud.githubusercontent.com/assets/5450820/19641037/96c063f0-9a09-11e6-9c5e-5917bcb8bb11.jpg)
**note**: My local address is 192.168.5.xxx

**Comment by Ritiek** [comment]
@vanbwodonk i use lighttpd for web servers. i do not think the problem is about tunneled connection (unless we want to use https/ssl) or lighttpd.
I am now able to connect to aria2 server from webui by assigning port 6800 on weaved and entering the generated url and port by weaved in the connection settings here http://ziahamza.github.io/webui-aria2/ , then it works ok.
I was hoping for a direct url generated by weaved which would work for web browsers and automatically connect to aria2 server on my pi and would let me do stuff.. anyways, this is not a bad idea too :)

Thanks for all the support everyone :D
