### ISSUE TITLE
uploaded data in detail view

### ISSUE THREAD

**Issue by Spider-Mann** [ziahamza/webui-aria2#271]
In the detail view of a torrents, the uploaded data is not updated automatically.

![uploaded](https://cloud.githubusercontent.com/assets/17256488/19550585/6e5829fa-96aa-11e6-8959-d691d801e641.png)

I have to update the window with F5 and then the language is always in English.

**Comment by carlnorum** [comment]
I think this might be the one I just fixed. https://github.com/ziahamza/webui-aria2/issues/310

**Comment by carlnorum** [comment]
https://github.com/ziahamza/webui-aria2/pull/309
