### ISSUE TITLE
Cannot connect the aria2 webui to aria2c with loopback

### ISSUE THREAD

**Issue by JayBeeDe** [ziahamza/webui-aria2#273]
Hi,

I don't understand why, I cannot connect aria webui to aria2c with the **localhost** or loopback ip **127.0.0.1**.. I use the default port **6800**.
If I use the private IP it works locally same thing with the public IP/dns by the way of a port translation. ok. But why not with the loopback? I want to do that in order to disallow the port used by aria2c in my router firewall. Indeed, aria2 webui is installed on the same server as aria2c.

```
root@raspberrypi:/ # ifconfig
eth0      Link encap:Ethernet
          ...

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:1034 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1034 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:80828 (78.9 KiB)  TX bytes:80828 (78.9 KiB)

root@raspberrypi:/ # netstat -tln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:139             0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:6800            0.0.0.0:*               LISTEN
...

root@raspberrypi:/ # cat /etc/hosts
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters

127.0.1.1       raspberrypi
```

Thank you for your help, I hope my question is not stupid...

**Comment by Ritiek** [comment]
@JayBeeDe  I had the same problem some time ago and then I realized that the IP address/port we feed into the WebUI is relative to the computer you are accessing the WebUI from.

What I mean is that you have aria2c and WebUI installed on your Raspberry Pi.
If you open the Web-UI on the Pi itself and change the connection settings to localhost:6800 - it will work and connect to aria2c server successfully.
but if you open the Web-UI from some other PC and then change the connection settings to localhost:6800 again it will fail to connect.
(the Web-UI thinks that the aria2c server is present on the PC you are accessing the Web-UI from but actually it is not, so it will fail even though the Web-UI we are accessing is present on the Pi)

**Comment by JayBeeDe** [comment]
Thanks, I really appreciate your answer.
Finally, what I did to get it working it's the following: Set up the private IP address with it's port, but it the configuration file, so that I don't have to set up it again.

**Comment by JayBeeDe** [comment]
Sorry for the writing mistakes above...
