### ISSUE TITLE
Running webui completely remotely

### ISSUE THREAD

**Issue by Steve-luo** [ziahamza/webui-aria2#276]
I'm running aria2 and webui-aria2 on my VPS as a remote downloading service.

Currently, webui relies on my computer to access my server. 
(To make this clearer, webui is creating a connection to my server from my computer, not directly connecting to the server)

How to make webui connect to my server directly through localhost, without the need to pass the connection through my computer?

**Comment by mgaulton** [comment]
look at something like local-tunnel or ngrok on the VPS maybe?

**Comment by ziahamza** [comment]
@mgaulton you would also have to host `webui` on the same VPS as `aria2`. You can perhaps use something like `apache server` or `nginx` to host both on the same domain/ip. `webui` should then auto connect to the server if port `6800` is open. 

It will still connect from browser to aria2 though and no way around it unfortunately ... but will make it seamless

**Comment by dschense** [comment]
just ssh tunnel to your remote machine:

ssh "your-remote-IP" -p "remote-ssh-port" -L 8080:localhost:80 -L 6800:localhost:6800 -l "your-ssh-user"
enter password of your remote ssh user and voila.

http://localhost:8080 and you see your remote webui with working rpc server.

**Comment by adamlove86** [comment]
@dschense thanks for this - i'm connecting to my raspberry pi just within my lan, but can't work out what to put for "remote-ssh-port". Generally i connect with "ssh ubuntu@raspberrypi.local", but when I enter the following:
`ssh raspberrypi.local -L 8080:localhost:80 -L 6800:localhost:6800 -l ubuntu`
but i get connection refused when accessing http://localhost:8080 in my browser
`channel 5: open failed: connect failed: Connection refused
channel 6: open failed: connect failed: Connection refused`
appreciate your help!

**Comment by devster31** [comment]
I would really like this as a feature.
I don't like connecting from my browser to a remote instance, especially if not hosted on a local network.
Using the WebUI as a bridge would allow, for example, a very easy SSL setup.
This would also facilitate the creation of Docker containers. One container could run the `aria2c` daemon, another the WebUI and the RPC port wouldn't need to be published.
