### ISSUE TITLE
[Feature Request]Batch Downloading from URI strings

### ISSUE THREAD

**Issue by jc3213** [ziahamza/webui-aria2#279]
For example, I'd like to download 20 files, named by
```
http://example.com/exam/ple1.jpg
http://example.com/exam/ple2.jpg
.....
http://example.com/exam/ple20.jpg
```

For now I have to add them one by one. I wonder if I can use http://example.com/exam/ple(1:20).jpg or http://example.com/exam/ple(1-20).jpg or some other format to merge all links into one single link like some other download managers(FDM, or IDM for example)??

Don't see any manual about this.

**Comment by ziahamza** [comment]
@jc3213 unfortunately this is not supported yet. You would have to file an issue with `aria2` directly for a feature like this

**Comment by jc3213** [comment]
Hmm, I thought this could be done by javascript. 

1st, convert batch link to download list(uris)
2nd, add download list(uris) to `aria2` download sessions

Anyway, thanks for your reply. I'll try to figure out how to do this in javascript then try to make pull request here (or just reply in this issue)

**Comment by binux** [comment]
you can download batch links with that format by both enable `--force-sequential` with `--parameterized-uri`

**Comment by jc3213** [comment]
@binux I've set the two option and tried http://comicride.jp/viewer/pupil/05/books/images/2/[1-50].jpg, it can't do batch download bug only downloaded 1.jpg . I've also tried [1-50:1].jpg, still no luck

**Comment by anthonyraymond** [comment]
Closing in favor of #67 where someone said that it succeed in using aria2 to batch downloads (still need webui implementation though)
