### ISSUE TITLE
[Feature Request] Incomplete download folder

### ISSUE THREAD

**Issue by danilodequeiroz** [ziahamza/webui-aria2#280]
Hey, It'd be useful to have two working folders one for incomplete downloads and another folder where completed files would be moved, since I found kinda confuse all those persistent .aria2 files .

**Comment by ziahamza** [comment]
@dzfacts this would require changing `aria2` configuration, and doesnt come in the scope of `webui`. Perhaps open an issue in the `aria2` main repo :)
