### ISSUE TITLE
aria webui as "JSON RPC Relay"

### ISSUE THREAD

**Issue by JayBeeDe** [ziahamza/webui-aria2#281]
Hi,

I'm using aria webui with aria2c on a raspberry pi. I finally get it working fine as I wanted, but...
I'm also using the Chrome extension [Aria2c Integration](https://chrome.google.com/webstore/detail/aria2c-integration/edcakfpjaobkpdfpicldlccdffkhpbfk) on my laptop. The problem is that the chrome extension has to connect directly to the aria2c daemon. For security reasons, I will prefer to connect the chrome extension to webui-aria2.

Is it possible to add a feature so that the aria webui can act as a "JSON RPC Relay", or to add an API for a third part chrome/firefox extension? Or create a chrome webui-aria2 extension for that?

Using a chrome extension is better, because you can just right click a link and send it to the aria2 download queue, without having to copy the link, open webui-aria2 and past it...

Thank for webui-aria2!

**Comment by ziahamza** [comment]
@JayBeeDe webui only runs in the browser, so it wont be able to have a `relay` feature. But if you do use the other extension, then those downloads should auto show in `webui` instantly.

**Comment by JayBeeDe** [comment]
Ok.
The problem is that I have to open a port on my router just for the extension, which is not so secure since it is only protected by a rpc secret
