### ISSUE TITLE
Feature request: Add file address by URL Fragment Identifier

### ISSUE THREAD

**Issue by alimadadi-info** [ziahamza/webui-aria2#283]
Hi @ziahamza ,

I was trying to create a browser extension for webui-aria2 but I had no clue how to pass URL to it.

It would be useful to automatically open "Add Downloads By URIs" modal if there is a request by URL's Fragment Identifier (I mean something like: http://aria2.dev/#add-uri:http://example.com/file.mp4). So the user just needs to install the extension, then whenever clicks on a url it opens webui-aria2 tab while "Add Downloads By URIs" modal is open and the file url is set, then just needs to click "start" button to start!

**Comment by ziahamza** [comment]
@alimadadi-info this would require adding routing to webui. This would involve something like `angular-router` integration, which wont be trivial. But I am open to contributions 😄

**Comment by morozov** [comment]
@alimadadi-info for a simple scenario you described, there's already [Aria2c Integration](https://chrome.google.com/webstore/detail/aria2c-integration/edcakfpjaobkpdfpicldlccdffkhpbfk) Chrome extension which can send links directly to `aria2c` over RPC w/o involving Web UI.
