### ISSUE TITLE
RPC won't connect having option "rpc-secure=true"

### ISSUE THREAD

**Issue by leandroong** [ziahamza/webui-aria2#285]
on terminal, I have no problem running with option "rpc-secure=true". If I included this on aria2.conf, configuration file, I will have connection problem. On other hand, no issue with option "rpc-secure=false". 
Is this an error?
Also, may I know how to have default check mark on "SSL/TLS encryption"? Is there I can edit in configuration.js ? Are there assurance that indeed it is encrypted when downloading? in terminal download it display downloading in encryption.

**Comment by leandroong** [comment]
checking "configuration.js", i saw encrypt default to false, setting to true will result in RPC connection problem.

**Comment by ziahamza** [comment]
@leandroong yea configuration is respected first. 

you can host webui in https as well, that way only https connection will work and rest will be blocked by browser (they will show a warning otherwise)
