### ISSUE TITLE
Forms do not support submission on Enter and Ctrl+Enter

### ISSUE THREAD

**Issue by morozov** [ziahamza/webui-aria2#295]
The "Add Downloads By URIs" form is so high that it doesn't fit a 1366×768 screen.

![aria2](https://cloud.githubusercontent.com/assets/59683/21631089/2315aad0-d1ec-11e6-826e-a257fdd72506.png)

After adding URIs into the textarea, one has to scroll down and click "Send". Especially in case when the "Advanced settings" section is expanded, it may be really annoying.

It would be more usable if this form (as well as others) supported submission on `Enter` in one-line fields and on `Ctrl+Enter` in textareas.

I don't know if there's a conventional way of doing this in AngularJS. If not, I can try implementing it in Javascript. Please let me know if you have any suggestions.

**Comment by ziahamza** [comment]
yea, auto text size would be pretty useful. I dont think we can get away with scrolling if advance settings are expanded as it will always push the button down though .

The text box may not save too much space TBH. Perhaps hide help by default?

**Comment by morozov** [comment]
> Perhaps hide help by default?

This definitely makes sense. It is useful for advanced use cases like mirrors and output file name. The examples themselves may be put into the textarea as placeholder. Once the user starts typing or pasting the URLs, they disappear.

> The text box may not save too much space TBH.

I brought up the form height to make the point about the necessity of being able to submit the form from keyboard. To me, it's a general usability improvement irregardless what the forms look like,

As for the form layout, I think the "Download Settings" section can be collapsed by default, same as "Advanced settings". The help block, instead of being displayed inline could be moved to a tooltip like below. It doesn't really belong inline, IMO.

![tooltip](https://cloud.githubusercontent.com/assets/59683/21652731/d36784b4-d262-11e6-8707-fc44db0c6f29.png)
