### ISSUE TITLE
file rename --out=

### ISSUE THREAD

**Issue by dschense** [ziahamza/webui-aria2#302]
everything is working like normal, but renaming a downloaded file ist a little bit buggy.
with:
`https://the-downloaded-file.test --out="This is a Testfile.test"`
it starts downloading, but names the File only as:
`This`
all stuff behind `is a Testfile.test` is missing

and when trying with --out="testfile.mkv" ist downloads, but is naming the file like:
`videoplayback`

is this my fault ?

**Comment by ziahamza** [comment]
@dschense This seems weird. Is the file not naming properly, or does webui shows the wrong filename?

**Comment by dschense** [comment]
@ziahamza it's not naming properly. I give it the name --out="test file.mkv" but in the dl directory the file is named "test" only.

**Comment by dan-saba** [comment]
I have the same issue. The web UI interface does not properly handle outputting files with spaces in their names, which is handled properly by the command-line interface. Please fix this bug ASAP.

**Comment by no1xsyzy** [comment]
## Steps to Reproduce
Add by URIs & Input this line：
`http://some.domain/and/path/to/page.html --out="some page.html"`

## Expected Result
Download to `some page.html`

## Unexpected Result
Trying to download to `"some`, which even failed on Windows.
`name resolution failed`

## Possible Reason of Problem
When tokenizing with params, the line above is tokenized to `http://some.domain/and/path/to/page.html`, `--out="some` and `page.html"`.

**Comment by no1xsyzy** [comment]
Work for several minutes and found this:
<https://github.com/ziahamza/webui-aria2/blob/master/js/ctrls/modal.js#L79>
After `parse` called, `http://some.domain/and/path/to/page.html --out="some page.html"` is parsed to:
```json
[
    [
        "http: //some.domain/and/path/to/page.html",
        "--out=\"some",
        "page.html\""
    ]
]
```
, which is unexpected
