### ISSUE TITLE
Default Pause mode for added URIs

### ISSUE THREAD

**Issue by Ornis** [ziahamza/webui-aria2#303]
How can I add an URI in pause mode by default?

I have to manually change pause to true -even if it's already true- in Download settings before click on start button, otherwise Aria start download immediately.

> **Aria2 Version 1.31.0**

>  **aria2.conf**

`pause=true`

> **settings.js**
```
  "pause": {
    desc: "Pause download after added. This option is effective only when --enable-rpc=true is given. Default: false",
    val: "true",
```
I've changed "pause" val: to "true" but didn't help.

**Comment by Suncatcher** [comment]
Changing pause to "True" in GUI mode worked for me. However, the difference between `Pause=True` and `--pause-metadata=True`  it [is not completely clear](https://github.com/ziahamza/webui-aria2/issues/76#issuecomment-276094469). Do you know it?
