### ISSUE TITLE
在线播放及下载问题

### ISSUE THREAD

**Issue by Tzbfire** [ziahamza/webui-aria2#314]
在线播放的的链接的download后面少了一个"/"导致不能在线播放或者下载，更换目录，还是http://url/download *

**Comment by myfreeer** [comment]
English, please.

**Comment by edking4967** [comment]
您可以给更多信息吗？我不太明白你的问题

**Comment by edking4967** [comment]
给我们logs的话应该帮助

**Comment by no1xsyzy** [comment]
我这里给出一个大胆的预测，你应该是在使用“连接设置”中的“直接下载”-“基本链接地址”：

环境：下载了文件`file.ext`。
你希望的内容：直接下载连接`http://url/download/file.ext`
你输入的内容：`http://url/download`
你得到的结果：`http://url/downloadfile.ext`

如果是这样的话，其实问题是设置中应该输入`http://url/download/`

**Comment by SatoSawa** [comment]
關於這個問題，其實README上有提到(在directurl.md中):
## Steps using linked download folder
...
7. scroll down to Direct Download and put http://serverip:81/downloads/ in base URL field (make sure have the / on the end)
...
