### ISSUE TITLE
Blank WebUI

### ISSUE THREAD

**Issue by Fourdee** [ziahamza/webui-aria2#318]
Hi guys,

Seems the recent merge breaks webui completely:
![image](https://cloud.githubusercontent.com/assets/7077026/24071712/84d38d8c-0bd0-11e7-8546-05f517b8d6a0.png)

Possible cause?
https://github.com/ziahamza/webui-aria2/pull/316/files#diff-8bdf25d2c2d3405d93634230f31b6960L115

If you need any more info, tests, please let me know.

---

Aria2c:
```
root@DietPi:~# systemctl status aria2 -l
● aria2.service - DietPi Aria2
   Loaded: loaded (/etc/systemd/system/aria2.service; disabled)
   Active: active (running) since Sat 2017-03-18 11:40:46 UTC; 8min ago
 Main PID: 9400 (aria2c)
   CGroup: /system.slice/aria2.service
           └─9400 /usr/local/bin/aria2c --enable-rpc --rpc-listen-all --rpc-secret=****** --dir=/mnt/dietpi_userdata/downloads

Mar 18 11:40:46 DietPi systemd[1]: Started DietPi Aria2.
Mar 18 11:40:46 DietPi aria2c[9400]: 03/18 11:40:46 [NOTICE] IPv4 RPC: listening on TCP port 6800
Mar 18 11:40:46 DietPi aria2c[9400]: 03/18 11:40:46 [NOTICE] IPv6 RPC: listening on TCP port 6800
```

**Comment by Fourdee** [comment]
Reverting to https://github.com/ziahamza/webui-aria2/tree/e54b454a0a4d7015d9c44f11f174347b042bda78 resolves the issue.

**Comment by Suncatcher** [comment]
Confirm this. But I am not hosting UI myself, so for me reverting is not an option. Please, fix http://ziahamza.github.io/webui-aria2/

**Comment by Fourdee** [comment]
All working, thanks to @pxia for the resolve.

**Comment by ziahamza** [comment]
Sorry for the delay here guys! let tag me directly with @ziahamza and I should be able to look into it ASAP.
