### ISSUE TITLE
How to set default values?

### ISSUE THREAD

**Issue by petrvecera** [ziahamza/webui-aria2#323]
Hello guys

For example I want to pre-define these settings:
![image](https://cloud.githubusercontent.com/assets/8086995/24462258/d3893c34-14a3-11e7-90f2-dadc7d928013.png)

aria.conf file:
```
dir=/root/var/html/www/aria/

split=8
max-connection-per-server=16
max-concurrent-downloads=8

http-user="TEST"
http-passwd="FUUU"
```

When I look into the global settings the http-user and passwd is set but not in the quick settings, any idea why ?

Thanks

**Comment by ziahamza** [comment]
@petrvecera you can actually change these values here: https://github.com/ziahamza/webui-aria2/blob/master/js/services/settings/settings.js

Change this, and refresh the page. All the settings, and their default values live there. Make sure you dont break anything though ... as changing in the wrong way is fragile and will break webui :)

**Comment by petrvecera** [comment]
Thanks! I think it would be nice to put this into the Config part in the main read.me
https://github.com/ziahamza/webui-aria2#configuration

It took me a moment to figure out that I have to use aria.conf file and how to write values there. 
As for the problem I have noticed that they are loaded and used when I put the link and start download , they are just not shown in the quick settings. So I have hidden all the quick settings which are already configured from the config file (global).

**Comment by cyaconi** [comment]
Hi!
I tried changing both configuration.js and settings.js and the web-gui keeps showing the default value. I also tried to change the default conf-path that points to my aria2.conf, but I couldn't find the key (it always shows "/etc/nginx/sites-available" but I don't know where is getting that value)

**Comment by anthonyraymond** [comment]
Be carefull with this, the `configuration.js` is exposed and can be accessed by anyone.
If you chose to set default values in `configuration.json` be sure not to open your webui to internet
