### ISSUE TITLE
Running on lighthttpd not working.

### ISSUE THREAD

**Issue by MainFighter** [ziahamza/webui-aria2#324]
I installed the webui on a RaspberryPi2 running lighthttpd and tried to get the web interface working from that but everytime I load it from the Pi it doesn't work shown in the image below.

https://i.imgur.com/8vi9zmD.png
![Image PI](https://i.imgur.com/8vi9zmD.png)

But then when I load it from my desktop with the same files (copied straight off the Pi) and same browser it loads perfectly fine shown below.
Desktop: http://i.imgur.com/8vK2fei.png
![Image Desktop](http://i.imgur.com/8vK2fei.png)

I have already tried changing the file owner and permissions on the Pi but that's the only reason I can think of why it wouldn't work. Is it something I misconfigured or does it just not working running of a webserver like that?

(I'm brand new to aria2, only just found it 30 minutes ago.)

EDIT: Blergh, sorry about the scaling on the images. Didn't consider how small the text would be in screenshots.

**Comment by anthonyraymond** [comment]
Closing because images links are dead, feel free to reopen if you still encounter issue with lighthttpd
