### ISSUE TITLE
当种子文件名长度过长，会超出界面

### ISSUE THREAD

**Issue by 0oVicero0** [ziahamza/webui-aria2#328]
如图所示
![20170405003346](https://cloud.githubusercontent.com/assets/11154604/24667895/900521b4-1997-11e7-82d8-51ee29ab1d67.png)

**Comment by LBYPatrick** [comment]
注意，由于作者是说英语的，所以建议使用英文表述这个问题...

**Comment by no1xsyzy** [comment]
更新到最新版本就可以了
![default](https://user-images.githubusercontent.com/7346170/28470420-3df70304-6e6c-11e7-8801-71f2bcd39108.png)
