### ISSUE TITLE
backend line in Dockerfile.arm

### ISSUE THREAD

**Issue by paulz1** [ziahamza/webui-aria2#331]
Just compiled (built) Dockerfile.arm for my raspberry.
The build was successful, but finally it does not work as expected. The webui is running, but could not connect to aria2 daemon.

It seems that the problem is in the goreman setup.

In the normal Dockerfile we have this line :

`RUN echo "web: gosu dummy /bin/busybox httpd -f -p 8080 -h /webui-aria2\nbackend: gosu dummy /usr/bin/aria2c --enable-rpc --rpc-listen-all --dir=/data" > Procfile`

while in Dockerfile.arm it's like :

`RUN echo "web: gosu aria /bin/busybox httpd -f -p 8080 -h /webui-aria2\nbackend: gosu aria /usr/bin/aria2c --conf-path=/data/.aria2/aria2.conf" > Procfile`

with the empty config 

`/usr/bin/aria2c --conf-path=/data/.aria2/aria2.conf `

do nothing, because it is waiting for some download url.

Should it be corrected, to have in the Dockerfile.arm the same backend line as in normal Dockerfile.

Or, if it should be configured with aria2.conf, I think it worth to mention it in Readme.

**Comment by ziahamza** [comment]
@paulz1 I think you are right. The latter is not starting aria2 in daemon mode. I shall fix!

**Comment by anthonyraymond** [comment]
I'm not really fan of hardcoring aria2 argument out of the config file.

Just add these two lines to `aria2.conf` and it works without hardcored values in dockerfile

```
enable-rpc=true
rpc-listen-all=true
```
