### ISSUE TITLE
Request: move finished downloads

### ISSUE THREAD

**Issue by Phill23** [ziahamza/webui-aria2#335]
Hi and thanks for the great work!
It would be awesome to be able to define a folder for complete downloads. 
This would be especially handy for the use of "whatcha folder" apps so they would not move incomplete files.

**Comment by azzamsa** [comment]
I think it's a good idea

**Comment by no1xsyzy** [comment]
No, aria2 doesn't provide a file operation interface, which is really a bad idea.

However, move after complete maybe not so bad, consider to raise issues at [aria2/aria2](https://github.com/aria2/aria2)
