### ISSUE TITLE
The download speed is not displayed

### ISSUE THREAD

**Issue by chenxk-j** [ziahamza/webui-aria2#337]
When I add the torrent task through the webUI, the task is displayed on the webUI and shows no download speed. But in the terminal can see the task is in downloading
![2017-04-19 8 37 22](https://cloud.githubusercontent.com/assets/17682324/25180423/8b6ed532-2540-11e7-9e9e-1f9e60176dfc.png)

**Comment by bawuju** [comment]
@chenxk-j I have the same problem, how do you solve it?
