### ISSUE TITLE
Changing Default Download Dir?

### ISSUE THREAD

**Issue by seanvree** [ziahamza/webui-aria2#341]
Windows 10E
Running Aria2 Web from IIS root
Aria2 running from Root c:\ as windows service with SYSTEM permissions

I'm new to Aria, so please excuse me. 

When I try to change the default global download Dir, it will change until I RESTART the Aria2 service then it will default back to C:\aria2... Not sure if this is a problem with the WebUI or the actual daemon....or I might just be a noob. 

Thanks!

**Comment by no1xsyzy** [comment]
You mean the global `dir` will become default AFTER restarting the service?
Don't mind too much, this should be a designed feature of Aria. It must read config file on startup and in the config file usually sets `dir`.
Delete or comment out that line with `#`, or change that to your option if you are not expecting saving in session.
