### ISSUE TITLE
How can I set a login password

### ISSUE THREAD

**Issue by Edelwiess** [ziahamza/webui-aria2#346]
I setup my aria2 on vps 
and aria2 webUI on same vps
Now anyone can use httpurl to access in to download thing on my vps.
I need to setup a password for webUI how can I do that?

**Comment by safiyat** [comment]
@Edelwiess You can use the [`--rpc-secret` switch](https://aria2.github.io/manual/en/html/aria2c.html#cmdoption--rpc-secret) with `aria2c` to enable a password for access.
You can also do it via a configuration file. The configuration file at `$HOME/.aria2/aria2.conf` should contain:
```
rpc-secret=<password>
```

**Comment by leoderbois** [comment]
I agreed, set password for the RPC is possible, but not for the WebUI, so everybody with the URL of my server can go to the webui and download file on my server. 

Somebody try a htaccess or something ?

**Comment by safiyat** [comment]
The web-UI can be accessed from anywhere! If you lock your UI with .htaccess, the attacker will use his own UI, but of course it won't work without authorizing RPC.

**Comment by imirzadeh** [comment]
If you want to run webui-aria2 on your own vps, you can use nginx:
https://www.digitalocean.com/community/tutorials/how-to-set-up-password-authentication-with-nginx-on-ubuntu-14-04

**Comment by alexya** [comment]
@Edelwiess I met the same issue. I only need to run aria2-webui in my local machine. Every time I have to input the "secret" to connect to my aria2 server. 
How did you resolve the issue? such as save or hard-code the secret to webUI local? 
Thx a lot.

**Comment by no1xsyzy** [comment]
@alexya use it on a domain, like <http://ziahamza.github.io/webui-aria2>, so that you won't need to input the secret, since the browser can remember it under that domain.
When using `files://` addresses, the system cannot determine the "domain" of the WebUI, thus impossible to save the secret.
