### ISSUE TITLE
Dockerfile not working under pi (error message included)

### ISSUE THREAD

**Issue by martinxusz** [ziahamza/webui-aria2#357]
hi, 
when i tried to run below commands " for testing purpose "(as mentioned in README.md),
i met error messages below, any ideas:
> $
pi@rspi ~/software/webui-aria2 $ docker build -t martinxu/webui-aria2 .
Sending build context to Docker daemon  24.66MB
Step 1/11 : FROM debian:8
 ---> 3e83c23dba6a
Step 2/11 : RUN apt-get update  && apt-get install -y aria2 busybox curl unzip  && rm -rf /var/lib/apt/lists/*
 ---> Running in c8f1a75bd867
standard_init_linux.go:178: exec user process caused "exec format error"
The command '/bin/sh -c apt-get update  && apt-get install -y aria2 busybox curl unzip  && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1
pi@rspi ~/software/webui-aria2 
$

this is my raspbian info:
>$
pi@rspi ~/software/webui-aria2 $ uname -a
Linux rspi 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l GNU/Linux
 >$

**Comment by skivvyxu** [comment]
after i changed the first line in Dockerfile, it's working fine,  maybe debian:8 is not suitable for pi ?
>$
#FROM debian:8
FROM resin/rpi-raspbian

**Comment by skivvyxu** [comment]
image building is fine, but not able to docker run:
>$
pi@rspi ~/Downloads $ docker run -it -v /home/pi/Downloads:/data -p 6800:6800 -p 9100:8080 --name="webui-aria2" martinxu/webui-aria2
standard_init_linux.go:178: exec user process caused "exec format error"

**Comment by andrii1812** [comment]
For pi build Dockerfile.arm
> standard_init_linux.go:178: exec user process caused "exec format error"
error is occured when you running x86 based images

**Comment by anthonyraymond** [comment]
@andrli1812 is right.

Use `docker build -f Dockerfile.arm -t martinxu/webui-aria2 .` to specify which Dockerfile to use.
