### ISSUE TITLE
Save current downloading files list

### ISSUE THREAD

**Issue by hamen** [ziahamza/webui-aria2#36]
Is there a way to save downloads list?
Every time I restart aria2, I have to re-add every previous file.
They resume fine and I'm happy with that, but I have to save every download url in case I need to resume it.
Am I missing something?
Thanks

**Comment by armavion** [comment]
> In order to use the function, you need to set the following options in your config file:
> --save-session=<SOME/WHERE>
> --continue=true
> --input-file=<SOME/WHERE> #must be same as save session
> 
> Find more here: http://aria2.sourceforge.net/manual/en/html/aria2c.html#synopsis

Thanks, it worked perfectly!
