### ISSUE TITLE
electron native app?

### ISSUE THREAD

**Issue by casouri** [ziahamza/webui-aria2#364]
Maybe you can make a native app with electron?

**Comment by ziahamza** [comment]
Possibly can with some helpers to save configurations. Would love to see someone package this into one 💯

**Comment by Kingbalou** [comment]
https://www.npmjs.com/package/nativefier can be a good start no need more specific dev for me

**Comment by anthonyraymond** [comment]
@Kingbalou you do need more specific dev (at least for the `configuration.js` file
