### ISSUE TITLE
DirectURL setting in configuration.js won't apply after modified

### ISSUE THREAD

**Issue by SatoSawa** [ziahamza/webui-aria2#365]
As mentioned by author, DircetURL's setting should be set in the file configuration.js then webUI will read it   
But after many times I tried, its not worked as expected.
Finally I found a temporary solution, in ```js/services/rpc/rpc.js``` :
``` javascript 
...
  var subscriptions = []
    , configurations = [authconf]
    , currentConf = {}
    , currentToken
    , timeout = null
    , forceNextUpdate = false;

  var cookieConf = utils.getCookie('aria2conf');
  // try at the start, so that it is presistant even when default authconf works
  if(cookieConf) configurations.unshift(cookieConf);
  if (['http', 'https'].indexOf(uri.protocol()) != -1 && uri.host() != 'localhost') {
    configurations.push({
      host: uri.host(),
      path: '/jsonrpc',
      port: 6800,
      encrypt: false,
      directURL: 'http://core:81/data_drive/'     // To add this line, as your DirectURL
    },
    {
      host: uri.host(),
      port: uri.port(),
      path: '/jsonrpc',
      encrypt: ( uri.protocol() == 'https' )
    },
    {
      host: uri.host(),
      port: uri.port(),
      path: authconf.path,
      encrypt: ( uri.protocol() == 'https' )
    });
  }
...
```   
After changing, you may need to clear the cookies. Then every time you visit aria2-webUI (even refresh the page, restart aria2-rpc server), the default DirectURL can be read.
I have no idea why configuration.js does not work (zero knowledge in AngularJS).

**Comment by no1xsyzy** [comment]
## Reproduction
### On Linux
when accessing through `file:///` then works well
using `http://localhost/some/path/` then not working

**Comment by no1xsyzy** [comment]
okay, found the problem. 
you should clean the cookies to make it working well. 
in order to clean cookies, you MUST leave the `index.html` page first, since it will constantly set cookie/set cookie when leaving page.

easy way is to leave the page and remove all cookies
better way is to remove the cookies using developer tools.

**Comment by SatoSawa** [comment]
@no1xsyzy You are correct. I should make sure the cookies of aria2-WebUI is completely clear first. Now configuaration.js works like a charm. Thank you for your help!

**Comment by recolic** [comment]
I cleared cookies in my browser but it doesn't work. I tried firefox and tried editing js/services/rpc/rpc.js and tried to change client. None of them works.
