### ISSUE TITLE
Add finder for download's dir

### ISSUE THREAD

**Issue by gthomasAdfab** [ziahamza/webui-aria2#369]
Hi I was wondering if it was possible to add a finder to find the directory where you want to download? We do not always know the right way to download, and I think that would be very useful.

Thank you for your reply.

**Comment by no1xsyzy** [comment]
I don't think aria2c provides an `ls`-like interface on RPC server, thus impossible. <https://aria2.github.io/manual/en/html/aria2c.html#methods>

This project really depends on the interfaces exposed by `aria2` (imagine `webui-aria2` and `aria2` on seperated servers and `aria2` server only exposes port 6800 for RPC, you cannot even know where is available to put)

If you are just confused by your own file system, try [my docker image for fully packed `aria2` and `webui-aria2`](https://hub.docker.com/r/no1xsyzy/packed-aria2) and use `-v /host/path/to/downloads:/downloads` in docker parameters to make everything clear and tidy.
