### ISSUE TITLE
Specify interface

### ISSUE THREAD

**Issue by adrianmihalko** [ziahamza/webui-aria2#372]
It is possible to specify which interface should be used for downloading?

aria2 documentation:

--interface=<INTERFACE>
Bind sockets to given interface. You can specify interface name, IP address and host name. Possible Values: interface, IP address, host name

**Comment by no1xsyzy** [comment]
For reference:
<https://aria2.github.io/manual/en/html/aria2c.html#cmdoption--interface>

I'm really new to GNU/Linux and not sure about what interface means. Does that means, for example, let aria2 download through LAN rather than WiFi?

**Comment by adrianmihalko** [comment]
Exactly, I hve multiple interfaces (devices) and I want to select another than the default.

**Comment by khunpoum** [comment]
its no working for me

**Comment by khunpoum** [comment]
this solution working right:  https://askubuntu.com/a/330128

**Comment by Mikii67** [comment]
Hi. 
About the aria2 --interface option:
This will work on my system and return the ip address of my VPN (tun11):
`curl --interface "tun11" https://ifconfig.co`

on the other hand, this will return the ip address of my default router connection (no VPN)
`aria2c --download-result=full  --interface=tun11  https://ifconfig.co`

So the question is: why would curl work effortlessly and aria2c won't?

thank you.

Michele

**Comment by no1xsyzy** [comment]
@Mikii67 I think you should create issue at https://github.com/aria2/aria2

**Comment by Mikii67** [comment]
Done now. Thanks for pointing that out.
