### ISSUE TITLE
账号密码错误 能否取消死循环似的自动重试

### ISSUE THREAD

**Issue by jonwinters** [ziahamza/webui-aria2#398]
用户体验极差，每次都会弹出账号密码输入框 然后又闪掉，用户输入的焦点被迫变动

**Comment by no1xsyzy** [comment]
Translate:

After failure of username/password test, the input box keeps showing up and disappearing.

另外，现在aria2c已经不推荐username/password验证了，token方案更好（因为一般不存在多用户的情况）

**Comment by jonwinters** [comment]
已经解决 直接写进configuration.js里面了

**Comment by no1xsyzy** [comment]
如果已经解决，为何不顺手关一下Issue呢

**Comment by jonwinters** [comment]
@no1xsyzy 已关
