### ISSUE TITLE
WebUI: Could not connect to the aria2 RPC server

### ISSUE THREAD

**Issue by Dedsic** [ziahamza/webui-aria2#400]
Platform : Brand new Windows 10 1709 without any customize. Aria2 version 1.33
Issue : I'm using a config file and it test just fine on other PC running same version of Windows, on real machine and virtualbox .
On my device, cmd shows that both IPv4 and IPv6 are listening on TCP port 6800, but the WebUI page could not connect to the aria2 RPC server.
My RPC server, by default , set as http(s)://localhost:6800/jsonrpc , perfect working on every device in my network environment except mine . I guess it's not a parameter problem.
Question : Any way to find more details about this issue or any solution to fix that?
Thanks.

**Comment by no1xsyzy** [comment]
* Take a look at browser's **Console Tab**, see if there is error.
* Take a look at **proxy setting**
* Try running aria2 in an **terminal window** instead of background, or see if there is error log.
* Dive into browser's **Network Tab** and see if they are exchanging information properly.
