### ISSUE TITLE
Certificate Issue?

### ISSUE THREAD

**Issue by Mattpenfold** [ziahamza/webui-aria2#401]
I am trying to configure access using HTTPS. The web-server is nginx, and that seems to handling the redirects from HTTP without a problem. 

I have aria2 configured to start with the command line parameters, --rpc-secure, --rpc-certificate and --rpc-private-key. 

The path for rpc-certificate points to  /etc/letsencrypt/live/dandderwen.com/fullchain.pem, and rpc-private-key to  /etc/letsencrypt/live/dandderwen.com/privkey.pem 

The certificate was created using certbox, for the domains dandderwen.com, www.dandderwen.com and aria2.dandderwen.com. They are configured in Nginx, and I do not get any warning about the certificates when access those domains. 

When I try to start aria2 I get the following error:

 Exception: [AbstractOptionHandler.cc:69] errorCode=28 We encountered a problem while processing the option '--rpc-certificate'.
:   -> [OptionHandlerImpl.cc:555] errorCode=1 Is '/etc/letsencrypt/live/dandderwen.com/fullchain.pem' a file?
Usage:
--rpc-certificate=FILE       Use the certificate in FILE for RPC server.
                               The certificate must be in PEM format.
                               Use --rpc-private-key option to specify the
                               private key. Use --rpc-secure option to enable
                               encryption.
                               Possible Values: /path/to/file
                               Tags: #rpc

Can anyone suggest what I might be doing wrong?

**Comment by no1xsyzy** [comment]
That seems a problem in aria2, try to post that to https://github.com/aria2/aria2/issues
