### ISSUE TITLE
下载过滤器勾选状态可以永久保存吗？

### ISSUE THREAD

**Issue by Gokou-Ruri** [ziahamza/webui-aria2#406]
![2017-11-22_142956](https://user-images.githubusercontent.com/26711804/33113196-0937ef0c-cf92-11e7-9f94-97e262dcd35f.png)
这个勾选的状态只要刷新页面或者换其它浏览器就会重置，请问有办法永久记忆这个过滤器设置吗？感谢！
附：使用 Windows10 + Chrome62

**Comment by no1xsyzy** [comment]
Translate:

> [feature request] hope the filter to be persist

**Comment by Gokou-Ruri** [comment]
@no1xsyzy 之前表达不清楚，我的想法是能不能将这部分的配置保存在configuration.js中，实现永久保存。（类似左侧边栏下方的“快速访问设置”那样）

**Comment by no1xsyzy** [comment]
Translate:

> Is filters configurable through `configuration.js`

可能性上应该是可行的，但不清楚目前版本是否可行，可能是一个feature request
