### ISSUE TITLE
有部分全局设置的项目输入框的类型好像不对吧？

### ISSUE THREAD

**Issue by Gokou-Ruri** [ziahamza/webui-aria2#407]
![2017-11-22_173625](https://user-images.githubusercontent.com/26711804/33120043-dc454746-cfab-11e7-82c0-8d586ec73a43.png)
比如“enable-dht”和“enable-dht6”的输入框类型应该是内容选择框吧？为什么是纯文本输入框？
而下方的“bt-enable-lpd”和“enable-peer-exchange”则是内容选择框。

**Comment by no1xsyzy** [comment]
竟然有选择框的吗……
我还以为是按照aria2的设置用的文本所以就文本了
我有时间看看能不能改了发个PR（大约下个月有空了，更早有谁要解决的话就解决了吧——不过不是故障）

Translate:

> settings like `enable-dht` and `enable-dht6` should be combo input like `bt-enable-lpd` or `enable-peer-exchange`

And I will find some time to fix that (but I will not be free until Dec 1st, when interim report of my final year project is due, feel free to fix it if any one want to fix earlier)

**Comment by Gokou-Ruri** [comment]
感谢！

**Comment by no1xsyzy** [comment]
Dumped all entries with "true" or "false" as content but not select
<https://gist.github.com/no1xsyzy/2e34843df5f972ca502ac0646d1d7d43>
It seems that all of them are not configured in [js/services/settings/settings.js](https://github.com/ziahamza/webui-aria2/blob/master/js/services/settings/settings.js) (for the time of writing [#77636e2/js/services/settings/settings.js](https://github.com/ziahamza/webui-aria2/tree/77636e25af04a965435519903ae09819ab727586/js/services/settings/settings.js))
