### ISSUE TITLE
Dockerfile not working under pi zero  (error message included)

### ISSUE THREAD

**Issue by yongqiang-xian** [ziahamza/webui-aria2#409]
error info:
02:19:38     web | Starting web on port 5000
02:19:38 backend | Starting backend on port 5001
02:19:38 backend | Exception caught
02:19:38 backend | Exception: [download_helper.cc:420] errorCode=1 Unrecognized URI or unsupported protocol: /data/downloads/*.torrent
02:19:38 backend | Terminating backend
02:24:31     web | Starting web on port 5000
02:24:31 backend | Starting backend on port 5001
02:24:31 backend | 12/02 02:24:31 [WARN] --rpc-user option will be deprecated in the future release. Migrate to --rpc-secret option as soon as possible.
02:24:31 backend | 12/02 02:24:31 [WARN] --rpc-passwd option will be deprecated in the future release. 
02:24:31 backend | Exception caught
02:24:31 backend | Exception: [download_helper.cc:420] errorCode=1 Unrecognized URI or unsupported protocol: /data/downloads/*.torrent
02:24:31 backend | Terminating backend

**Comment by smilingpoplar** [comment]
pi 3b 也是这有这问题

**Comment by ziahamza** [comment]
@yongqiang-xian the issue should be fixed with this PR: https://github.com/ziahamza/webui-aria2/pull/414

Please webui-aria2 and let me know if you still face the issue 🙏

**Comment by smilingpoplar** [comment]
@ziahamza #414 still not work. same error.

**Comment by smilingpoplar** [comment]
@ziahamza Manually build takes too many time for each user. Why not use dock-hub's auto build service? Just link your github to docker-hub: https://docs.docker.com/docker-hub/builds/#build-statuses-explained

**Comment by smilingpoplar** [comment]
@ziahamza #414 seems irrelevant.
@anthonyraymond the change of " in the line of Dockerfile.arm is related? 
```
- RUN echo "web: gosu aria /bin/busybox httpd -f -p 8080 -h /webui-aria2\nbackend: gosu aria /usr/bin/aria2c --conf-path=/home/aria/.aria2/aria2.conf" /data/downloads/*.torrent > Procfile
+ RUN echo "web: gosu aria /bin/busybox httpd -f -p 8080 -h /webui-aria2\nbackend: gosu aria /usr/bin/aria2c --conf-path=/home/aria/.aria2/aria2.conf /data/downloads/*.torrent" > Procfile
```

**Comment by ziahamza** [comment]
Aaah that seems to be it @smilingpoplar ! Do you want to make a PR for the fix, or else I can make one!

**Comment by anthonyraymond** [comment]
What if you add 
```
continue=true
check-integrity=true
```

to your config file? And do you have any .torrent files in the specified folder?

**Comment by smilingpoplar** [comment]
@ziahamza @anthonyraymond 
I'm not sure if that's the problem. Building aria2 from src take hours. The Dockerfile.arm never works for my arm7 raspberry pi.

**Comment by anthonyraymond** [comment]
It does works on mine, let's see what is the difference between ours instances:

Here is my host directory tree:
```
/home/anthony/data/aria2/
/home/anthony/data/aria2/downloads
/home/anthony/data/aria2/downloads/ad4edd302c1927a03050cdc4c52ab1424c4335e8.torrent
/home/anthony/data/aria2/.aria2
/home/anthony/data/aria2/.aria2/aria2.log
/home/anthony/data/aria2/.aria2/aria2.conf
/home/anthony/data/aria2/.aria2/.cache
/home/anthony/data/aria2/.aria2/.cache/aria2
/home/anthony/data/aria2/.aria2/.cache/aria2/dht.dat
/home/anthony/data/aria2/.aria2/.cache/aria2/dht6.dat
/home/anthony/data/aria2/.aria2/session.txt
```

Here is my config (/data/aria2/.aria2/aria2.conf on the host)
```
file-allocation=none
dir=/data/downloads
max-overall-upload-limit=0
max-upload-limit=0
max-concurrent-downloads=80
max-connection-per-server=4
continue=true
check-integrity=true
enable-rpc=true
rpc-listen-all=true
rpc-listen-port=XXXXX
rpc-secret=XXXXXXXX
disable-ipv6=true
summary-interval=120
disk-cache=64M
timeout=600
retry-wait=30
max-tries=50
save-session=/home/aria/.aria2/session.txt
log=/home/aria/.aria2/aria2.log
log-level=error
seed-ratio=0.0
seed-time=22000
enable-dht=false
enable-dht6=false
enable-peer-exchange=false
```

Here is my command line to start the docker container: (there is no port mapping because i'm using a vpn container as my network)
```
docker run \
            -v /home/anthony/data/aria2/downloads:/data/downloads \
            -v /home/anthony/data/aria2/.aria2:/home/aria/.aria2 \
            --name="aria2" \
            -d ziahamza/webui-aria2
```

**Comment by smilingpoplar** [comment]
@ziahamza @anthonyraymond finally I make it work on my pi, I've open a pull request

**Comment by smilingpoplar** [comment]
@anthonyraymond I add 
```
continue=true
check-integrity=true
```
not working. 

When I have touch a a.torrent file in download dir, it says "errorCode=1 Unrecognized URI or unsupported protocol: /data/downloads/a.torrent"

**Comment by anthonyraymond** [comment]
What if you put a real .torrent file?

**Comment by smilingpoplar** [comment]
@anthonyraymond It works after putting a real .torrent file.

That's werid for a first time user. You can't start up the service if there's no .torrent file.

**Comment by anthonyraymond** [comment]
yeah... i'll have to find an expression that return `""`if there is no .torrent in the folder.

It looks like `/data/downloads/*.torrent is evaluated` as `/data/downloads/.torrent` if there is no torrent.
I'll try to fix this soon

**Comment by smilingpoplar** [comment]
btw, when you update it, could you update the aria2 installation part as
```
# webui + aria2
RUN apt-get update \
	&& apt-get install -y aria2 busybox curl unzip git \
	&& rm -rf /var/lib/apt/lists/*

ADD . /webui-aria2
```
build from src is time consuming.

**Comment by anthonyraymond** [comment]
Hum :/ i don't thinks that's a good idea. the apt repo version is really out to date. They does not seems to maintain the arm distrib.

Otherwise, i agree that it's really slow to build from source, but since it's at the begining of the Dockerfile it should be cached, unless the first `RUN` is changed between version (which only happens when aria2 is updated)

**Comment by smilingpoplar** [comment]
Well, it seems not cached well. Each time I `docker build`, the aria2 building process takes nearly an hour... Maybe we should try https://docs.docker.com/docker-hub/builds/#link-to-a-hosted-repository-service

**Comment by anthonyraymond** [comment]
That's weird, do you run docker rmi before building?

**Comment by smilingpoplar** [comment]
no..I can't remember..maybe..

**Comment by anthonyraymond** [comment]
If you don't remove the image with `rmi` the image layer is supposed to be used.

**Comment by smilingpoplar** [comment]
@anthonyraymond I think we could use
```
`find /data/downloads -name '*.torrent'`
```
to replace /data/downloads/*.torrent

**Comment by anthonyraymond** [comment]
`find .` will be fucked up if you put a torrent file with space in the file name. 😞

**Comment by smilingpoplar** [comment]
yes, I found that too. couldn't resume torrent name with space

**Comment by anthonyraymond** [comment]
I may have find out somethink, i'll try it tonight 😃

**Comment by anthonyraymond** [comment]
#416 Will fix the issue with no torrent on start.
