### ISSUE TITLE
feature request：connect to different servers via URL prameters

### ISSUE THREAD

**Issue by h2y** [ziahamza/webui-aria2#410]
webui as a aria2 client, i can only connect to the only server saved in config.js . if user want to connect to another one, the only way is download the project again, and write another config again. 

in my opinion, use URL hash is the best solution, just like:
`https://ziahamza.github.io/webui-aria2/#server=hzy.pw:6800&password=xxx`

if there are hash string, configs in config.js file will be ignored.

so, we can use one copy of  the project's code but connect to any servers with different URLs.

**Comment by maz-1** [comment]
You may want to try aria-ng, which supports multiple jsonrpc configs
https://github.com/mayswind/AriaNg

**Comment by h2y** [comment]
yes, and it will be a useful feature.

**Comment by no1xsyzy** [comment]
How about keeping 2 copies of webui-aria2?
Well, this feature will be also useful.
