### ISSUE TITLE
怎么设置单文件最大连接数为256？

### ISSUE THREAD

**Issue by zlf179** [ziahamza/webui-aria2#411]
每当我在WebUI上添加任务的时候设置最大连接数为256的时候，就显示这样的报错
We encountered a problem while processing the option '--max-connection-per-server'.
难道只能设置为16吗？16的话速度上不去啊

**Comment by no1xsyzy** [comment]
Translate:

> # How to set max connection of single file to 256?
> Whenever adding task with max-connection-per-server=256 there gives such error:
> > We encountered a problem while processing the option '--max-connection-per-server'.
> Only up to 16 can be set? That is too slow.

English only. (with your dictionary is better than with your Chinese - the project owner seems don't read Chinese, and I seems to be the only issue translator for now...)
Check this: <https://github.com/aria2/aria2/issues/1039> This limit is hard coded in `aria2`.
What's more, 256 connections don't really help. If you really need, you can always fork one and change the limit.

@ziahamza An `aria2`-related problem, directly close plz.

**Comment by Gokou-Ruri** [comment]
因为默认参数编译的aria2最大连接数只能设置为16，你可以自己修改参数重新编译aria2。

**Comment by ziahamza** [comment]
@no1xsyzy closed as you suggested :)
