### ISSUE TITLE
下载BT文件之前，能筛选文件下载吗？

### ISSUE THREAD

**Issue by Gokou-Ruri** [ziahamza/webui-aria2#412]
比如直接添加一个种子或磁链，能够像传统的BT下载GUI那样，筛选需要的文件进行下载，取消不需要的文件吗？因为有时候一个BT种子里会包含几千个文件。

**Comment by no1xsyzy** [comment]
这个 #368 就已经实现了
只要添加种子或磁链之前先pause=true，出现任务之后任务的右边会有选择任务文件选项，是文件结构的。

**Comment by mingxiruoxi** [comment]
ria2c -S target.torrent #列出种子内容
aria2c --select-file=<INDEX> target.torrent #下载指定编号的文件，比如 1，3-5
