### ISSUE TITLE
可以下载文件，但不能删除文件

### ISSUE THREAD

**Issue by eaglexiang** [ziahamza/webui-aria2#413]
在webui中删除任务后，文件本体仍会被保留在硬盘中

**Comment by no1xsyzy** [comment]
这是预期的结果，因为aria2不会删除任何本地文件，这一点已经被aria2社区讨论过并得出结论了：不会提供文件管理功能。
如果希望在网页端操作文件系统，请使用ownCloud或者类似的软件。

**Comment by eaglexiang** [comment]
@no1xsyzy 谢谢，只是我挺好奇，为什么webui不考虑想办法加入这个功能呢？因为这的确是痛点呀。

**Comment by no1xsyzy** [comment]
@eaglexiang 因为这只是前端项目，有时候如果aria2不告诉你，你甚至不知道aria2运行在什么服务器上（win-x86|linux-x86|linux-arm|bsd|darwin|hurd，甚至可以patch后编译为安卓或者iOS的App(虽然上不了应用商店)）。这另一方面可能涉及Unix哲学：Do one thing and do it best。很多时候可以ssh到服务器里管理文件，aria2做得再好也难有bash好。

**Comment by eaglexiang** [comment]
@no1xsyzy 有道理。不过我们并一定要依赖aria2提供后端支持吧。我们的确可以使用ssh管理文件，但我们同样可以通过ssh使用aria2，这并不妨碍webui-aria2存在的价值。还是说没有提供此类支持的方案？如果存在的话，webui是否会考虑呢？

**Comment by no1xsyzy** [comment]
这只是前端方案，你在浏览器里能做的事情就是在一个有限沙盒内运行JS和调用目标host的API。aria2-webui要能够控制文件系统就必须要目标host具有某种API可以控制其文件系统，但无论选择哪一个API都会导致过耦合/捆绑销售。这种行为已经被贬斥了相当多了（想想百度全家桶）。

而且大多数的aria2连接都是未加密的（aria2的token也是明码发送），连csrf都没处理。通过API控制文件通常没有足够的加密处理。通常的云端也罢了，有https只要注意页面地址还不会有大问题，只有mega、lastpass（不确定）、iCloud钥匙串等很少的服务是真正意义上的加密（而不仅仅是加密链接，连网站自己都不知道你的密码和你存储的内容）。想象要是谁弄个私人云端是这样不安全的，一天大约能有上百G的私人资料持续流出。所以webui-aria2极难处理这一问题。

另一方面，webui-aria2的开发日渐趋缓，因为本身已经足够好用。很难再去弄一个如此大的功能（估计代码量要翻倍）。再一方面webui-aria2主打轻量无部署，添加aria2以外的功能显然会导致太多问题。
