### ISSUE TITLE
安装依赖库zlib-1.2.11 c-ares-1.13.0 libssh2-1.8.0时出错，怎么解决

### ISSUE THREAD

**Issue by a48625a** [ziahamza/webui-aria2#420]
1、安装zlib
cd zlib-1.2.11 && \
    CC=$HOST-gcc \
    AR=$HOST-ar \
    LD=$HOST-ld \
    RANLIB=$HOST-ranlib \
    STRIP=$HOST-strip \
    ./configure \
        --prefix=/usr/local/$HOST \
        --libdir=/usr/local/$HOST/lib \
        --includedir=/usr/local/$HOST/include \
        --static && \
    make install
提示：
Compiler error reporting is too harsh for ./configure (perhaps remove -Werror).
** ./configure aborting.

2、安装c-ares
cd c-ares-1.13.0 && \
    ./configure \
        --disable-shared \
        --enable-static \
        --without-random \
        --prefix=/usr/local/$HOST \
        --host=$HOST \
        --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` \
        LIBS="-lws2_32" && \
    make install
提示：
checking whether the C compiler works... no
configure: error: in `/home/q/c-ares-1.13.0':
configure: error: C compiler cannot create executables
See `config.log' for more details

3、安装libssh2
cd libssh2-1.8.0 && \
    ./configure \
        --disable-shared \
        --enable-static \
        --prefix=/usr/local/$HOST \
        --host=$HOST \
        --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` \
        --without-openssl \
        --with-wincng \
        LIBS="-lws2_32" && \
    make install
提示：
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/home/q/libssh2-1.8.0':
configure: error: C compiler cannot create executables
See `config.log' for more details

**Comment by myfreeer** [comment]
Your gcc fails. Try re-installing building tolchain.

**Comment by maz-1** [comment]
Problem with aria2 itself should not go here, I think.
https://github.com/aria2/aria2
