### ISSUE TITLE
webui-aria2 not downloading correctly with filehippo.com

### ISSUE THREAD

**Issue by leandroong** [ziahamza/webui-aria2#421]
Fliehippo.com site does not provide direct-download url. Temporary solution, I let it download initially, inside firefox browser, pause and copy download link and paste in webui-aria2. 
Can you enhance your app to retrieve the actual direct-download url?

**Comment by no1xsyzy** [comment]
I cannot access to that web site, but I have method to solve that:
<https://github.com/RossWang/Aria2-Integration>, a Firefox plugin to capture every download and try adding to aria 2. [Also available on AMO](https://addons.mozilla.org/firefox/addon/aria2-integration/)

BTW, I think your "direct-download url" refers to "real download URL": they are concealled and encrypted.

**Comment by leandroong** [comment]
Perfect, it shows real download url in the download dialog. F or info, My aria2 server running on my router and not on windows. Thanks


Sent from Mail for Windows 10

**Comment by no1xsyzy** [comment]
Please notice that the plugin can be configured to add download to aria 2 on other hosts, which you may find useful.

**Comment by leandroong** [comment]
Experimenting ATM, I was able to see aria2 connected but not downloading or added in my https://10.0.1.1/aria2/index.html. Any idea?

Sent from Mail for Windows 10
