### ISSUE TITLE
How to pass cookies for HTTP downloads?

### ISSUE THREAD

**Issue by sofakng** [ziahamza/webui-aria2#423]
Is it possible to pass cookies (or load a cookie file) with the web ui?

I've added load-cookies=/conf/cookies.txt to my aria2.conf, but when I add a file using the web ui, it doesn't send the cookies to the website.

**Comment by no1xsyzy** [comment]
You cannot specify cookie of task by RPC settings. There seems no `load-cookies` in RPC interface.
But you can use header to include cookies for each task.

**Comment by sofakng** [comment]
Thanks for the answer!
