### ISSUE TITLE
could not create directory.

### ISSUE THREAD

**Issue by Bubbab123** [ziahamza/webui-aria2#425]
I don' t know how to fix the problem. I use chmod 755 /yourdir, but showed No such file or director.

**Comment by no1xsyzy** [comment]
To change mode, you should create the file/directory first.
Issues about file system/shell. Not webui-aria2 related

**Comment by Bubbab123** [comment]
So basically, that's the files' problems? Any idea to solve it? Like how do I create the file/directory?

**Comment by Bubbab123** [comment]
Oh sorry I have already fixed it.  I tried again and it worked.
