### ISSUE TITLE
Hi,how can I change the configuration to maximize my download speed?

### ISSUE THREAD

**Issue by Xiechengqi** [ziahamza/webui-aria2#426]
The download speed of my home can reach to 10M/s.However,the download speed of this method is only about 1M/s，so how can I change the configuration to maximize my download speed?Thanks!

**Comment by no1xsyzy** [comment]
Check `max-overall-download-limit` of global and `max-download-limit` of each download.
`max-connection-per-server`(value max to 16) sometimes helps.
Otherwise, there is few thing you can do.
