### ISSUE TITLE
[Feature Request] RSS Feed Support

### ISSUE THREAD

**Issue by zero77** [ziahamza/webui-aria2#429]
Can you please add support for monitoring and downloading from RSS feeds.
Thanks

**Comment by no1xsyzy** [comment]
Nothing is kept running for monitoring.
That requires the browser tab kept open and the site with RSS has a cross-domain header, which mostly don't.
Or, you can write a little Python or Ruby or even Shell script with `cron` or Scheduled Tasks to monitor the RSS Feed for you. The interface of aria2 is open to you.
