### ISSUE TITLE
webui problem with samsung internet (v6.2.01.12) in android

### ISSUE THREAD

**Issue by imanmoghimiq30** [ziahamza/webui-aria2#430]
any button didn't work in samsung internet
![screenshot_2018-02-06-18-35-30](https://user-images.githubusercontent.com/33248902/35866576-d6c3b940-0b6c-11e8-89da-c7052a48939a.png)
![screenshot_2018-02-06-18-35-27](https://user-images.githubusercontent.com/33248902/35866659-0a513dd2-0b6d-11e8-84c5-9d0ce1f1b0aa.png)

**Comment by imanmoghimiq30** [comment]
webui problem with samsung internet (v6.2.01.12) in android

**Comment by no1xsyzy** [comment]
It seems angular is not supported on that browser. Maybe there are some polyfills or transpilers that can work but not sure.

**Comment by anthonyraymond** [comment]
#307
