### ISSUE TITLE
Can't connect to remote aria2 rpc interface

### ISSUE THREAD

**Issue by http403** [ziahamza/webui-aria2#440]
I set up a CentOS 7 machine on DigitalOcean with aria2 1.33.1. However, the web UI (run on my local computer) cant connect to it. The only successful experience is connect to a local aria2 RPC instance. How could I fix it?

**Comment by no1xsyzy** [comment]
Check command line/config file about `rpc-listen-all`. This should be set true while its default value is false.
Without this as `true`, aria2 will bind on localhost, which makes only connections from the host itself is accepted.

**Comment by http403** [comment]
Yeah, I did turn that option on. I even drop my VPS firewall totally. Still no luck.

**Comment by http403** [comment]
It seems the UI want to work now. I will reopen if happen again.
