### ISSUE TITLE
Blank WebUI

### ISSUE THREAD

**Issue by flatlinebb** [ziahamza/webui-aria2#442]
Similar to issue https://github.com/ziahamza/webui-aria2/issues/318
The webpage is blank when going to https://ziahamza.github.io/webui-aria2/
Not sure if this will help, but this is the error in Chrome console:

    Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.6.0/$injector/modulerr?p0=webui&p1=TypeError%3A%20Cannot%20read%20property%20'Search'%20of%20undefined%0A%20%20%20%20at%20mergeTranslation%20(https%3A%2F%2Fziahamza.github.io%2Fwebui-aria2%2Fjs%2Finit.js%3A22%3A19)%0A%20%20%20%20at%20https%3A%2F%2Fziahamza.github.io%2Fwebui-aria2%2Fjs%2Finit.js%3A46%3A30%0A%20%20%20%20at%20Object.invoke%20(https%3A%2F%2Fziahamza.github.io%2Fwebui-aria2%2Fjs%2Flibs%2Fangular.min.js%3A43%3A175)%0A%20%20%20%20at%20d%20(https%3A%2F%2Fziahamza.github.io%2Fwebui-aria2%2Fjs%2Flibs%2Fangular.min.js%3A41%3A64)%0A%20%20%20%20at%20https%3A%2F%2Fziahamza.github.io%2Fwebui-aria2%2Fjs%2Flibs%2Fangular.min.js%3A41%3A188%0A%20%20%20%20at%20q%20(https%3A%2F%2Fziahamza.github.io%2Fwebui-aria2%2Fjs%2Flibs%2Fangular.min.js%3A7%3A351)%0A%20%20%20%20at%20g%20(https%3A%2F%2Fziahamza.github.io%2Fwebui-aria2%2Fjs%2Flibs%2Fangular.min.js%3A40%3A488)%0A%20%20%20%20at%20eb%20(https%3A%2F%2Fziahamza.github.io%2Fwebui-aria2%2Fjs%2Flibs%2Fangular.min.js%3A45%3A56)%0A%20%20%20%20at%20c%20(https%3A%2F%2Fziahamza.github.io%2Fwebui-aria2%2Fjs%2Flibs%2Fangular.min.js%3A21%3A19)%0A%20%20%20%20at%20Object.Lc%20%5Bas%20bootstrap%5D%20(https%3A%2F%2Fziahamza.github.io%2Fwebui-aria2%2Fjs%2Flibs%2Fangular.min.js%3A21%3A332)
    at angular.min.js:6
    at angular.min.js:41
    at q (angular.min.js:7)
    at g (angular.min.js:40)
    at eb (angular.min.js:45)
    at c (angular.min.js:21)
    at Object.Lc [as bootstrap] (angular.min.js:21)
    at HTMLDocument.<anonymous> (init.js:66)
    at i (jquery-2.2.4.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-2.2.4.min.js:2)

I was able to download the older build (https://github.com/ziahamza/webui-aria2/tree/e54b454a0a4d7015d9c44f11f174347b042bda78)
And running it locally it works as expected, so I know that my aria2c is running correctly. I prefer the https://ziahamza.github.io/webui-aria2/ site. Please fix @ziahamza 

![image](https://user-images.githubusercontent.com/4769578/36398139-7774f77a-157a-11e8-975c-95245035c7c0.png)

**Comment by baoang** [comment]
the same problem. I tried download the git, save the webpage, and even tried node.js approach. all failed.

**Comment by flatlinebb** [comment]
It's fixed for me - thank you!
