### ISSUE TITLE
A statistic page/tab

### ISSUE THREAD

**Issue by http403** [ziahamza/webui-aria2#443]
I would like to have a statistic page/tab on different category (e.g. HTTP/FTP/BT) which list out how many downloaded/uploaded/share ratio in a specific range of days, like 30 or 60 days.

**Comment by no1xsyzy** [comment]
No possibility for that. I don't think aria2 has provided such interface. And you can notice that all statistics and graphs cannot preserve after the page is closed.

**Comment by no1xsyzy** [comment]
With about 10 hours of learning and training, you can make a data collector and a graph plotter with Python (+requests and matplotlib).
And with another hour of learning and training, you can find out ways to collect data periodically (with Task Scheduler on Windows or cron/crontab on Unix-like), or keep it up with Python Supervisor.
Hope that would help :)
