### ISSUE TITLE
Super long file list

### ISSUE THREAD

**Issue by http403** [ziahamza/webui-aria2#444]
If a torrent contains a lots of files, the whole page is swarmed with the file list which makes browsing difficult. Is there any better options to display them?

**Comment by no1xsyzy** [comment]
You can collapse the detailed information.

**Comment by http403** [comment]
I need speed graph constantly which won't display unless extend the detailed info.

**Comment by no1xsyzy** [comment]
How about user styles/user scripts? That would be a temporary solution.
I have seen that the functionality would be useful, however, I haven't got a good UX design in my mind so far. Any suggestions about this?

**Comment by http403** [comment]
User styles/scripts might to too complicated. Maybe a "theme" alike function let user install what layout they like? Or take Foobar2000's approach, an interactive UI design tool to simplify the complexity?

**Comment by no1xsyzy** [comment]
User styles just contain one selector and `display: none;`. It wouldn't be so difficult.
I thought it easier with React.js. But if you go too far away from it, you would just make another WebUI. To make matters worse, it is difficult to manage with plugins in browser.
I think what best fits your requirement is a python script collecting data and display with `matplotlib`.
