### ISSUE TITLE
无法连接有两个网络端口的VPS RPC服务

### ISSUE THREAD

**Issue by lizhaode** [ziahamza/webui-aria2#445]
```
不好意思，我的英语不好，只好用中文了。如果有哪位朋友有时间，请帮我翻译一下，万分感谢!
```

前提条件：
1. conf配置文件是正确的，因为同样的文件在别的VPS上正常
2. iptables正确
3. 机器网络正常，因为 ss-libev 服务使用正常
4. 本地使用的webui-aria2 配置正确，因为同样的配置仅更改ip即可连接别的VPS上aria2 RPC

出问题的 VPS  上 ifconfig 打印结果如下（地址用xx来代替）：

```
enp0s5    Link encap:Ethernet  HWaddr 00:1c:42:51:a9:2f  
          inet addr:10.79.132.248  Bcast:10.79.255.255  Mask:255.248.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:90 (90.0 B)  TX bytes:0 (0.0 B)

enp0s6    Link encap:Ethernet  HWaddr 00:1c:42:68:bb:ce  
          inet addr:xx.xx.xx.xx  Bcast:xx.xx.xx.xx  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:23561837 errors:0 dropped:226859 overruns:0 frame:0
          TX packets:2858642 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:7627912171 (7.6 GB)  TX bytes:6478861383 (6.4 GB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:796345 errors:0 dropped:0 overruns:0 frame:0
          TX packets:796345 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:6289814416 (6.2 GB)  TX bytes:6289814416 (6.2 GB)
```
复现步骤：
1. VPS上使用 apt install aria2安装
2. 从正常能用的VPS上拷贝正在使用中的aria2.conf文件
3. aria2c --conf-path=aria2.conf 来启动
4. 本地电脑打开webui-aria2网页，配置正确的 ip地址 等配置 

实际结果：
等一会后提示无法连接，Chrome的开发者工具中显示 ws 连接超时

备注：
出问题的VPS上 aria2c -v 显示如下：

```
aria2 version 1.33.1
Copyright (C) 2006, 2017 Tatsuhiro Tsujikawa

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

** Configuration **
Enabled Features: Async DNS, BitTorrent, Firefox3 Cookie, GZip, HTTPS, Message Digest, Metalink, XML-RPC
Hash Algorithms: sha-1, sha-224, sha-256, sha-384, sha-512, md5, adler32
Libraries: zlib/1.2.11 libxml2/2.9.4 sqlite3/3.21.0 GnuTLS/3.5.8 nettle GMP/6.1.2 c-ares/1.13.0
Compiler: gcc 7.2.0
  built by  x86_64-pc-linux-gnu
  on        Jan  5 2018 16:55:22
System: Linux 4.15.0-10-generic #11-Ubuntu SMP Tue Feb 13 18:23:35 UTC 2018 x86_64

Report bugs to https://github.com/aria2/aria2/issues
Visit https://aria2.github.io/
```

**Comment by no1xsyzy** [comment]
试一下本地机器上`curl -D - '<json-rpc address>'`，看看jsonrpc是否正常。

目前的能作的猜测：端口没绑定成功。`netstat -ano|grep 1080`查一下有没有aria2c进程（最后一列是PID），绑在哪个接口上。

还有一些可能性的尝试。
通过ss访问aria2rpc；检查防火墙。

**Comment by lizhaode** [comment]
@no1xsyzy 

netstata 的结果是这样的
```
tcp        0      0 0.0.0.0:6800            0.0.0.0:*               LISTEN      off (0.00/0/0)
```

**Comment by lizhaode** [comment]
curl命令的结果是这样的

```
curl: (6) Could not resolve host: <json-rpc xx.xx.xx.xx>
```
ip地址用xx代替

**Comment by no1xsyzy** [comment]
DNS解析失败，考虑`dig`或者`nslookup`分析DNS记录。
如果是直接的IP地址，看看有没有写错（比如`1l`和`0O`，或者某一分块超出255）

**Comment by lizhaode** [comment]
@no1xsyzy 
分块超出255是指什么？我能确定IP地址没问题，因为搭在这个机器上的ss是正常工作的

**Comment by no1xsyzy** [comment]
我说的255是指比如256.256.256.256这种……
慢着，我是说把`<json-rpc address>`这整个换成RPC地址（比如`curl -D - 'http://localhost:6800/jsonrpc‘`），Windows记得换成双引号。

**Comment by lizhaode** [comment]
原来如此，我又按照这样输入的 `curl -D - 'http://xx.xx.xx.xx:6800/jsonrpc'`

并且还在服务端关闭了aria2配置文件中的密码
输出结果是超时

```
curl: (7) Failed to connect to xx.xx.xx.xx port 6800: Operation timed out
```
这样是不是其实6800端口没有打开？但是我netstat能看到端口打开，且绑定在0.0.0.0了

**Comment by lizhaode** [comment]
而且我发给vps商询问了，他们并没有针对aria2有什么限制

**Comment by no1xsyzy** [comment]
其实和密码没什么关系……如果有密码aria2会返回密码错误。
之后的部分我自己处理的话多半是靠运气和灵感，所以很遗憾并不能进行任何确切有用的帮助。只能说一下目前看来可能的试探：
1. tcpdump/wireshark 分析网络流量数据；
2. 检查netstat -ano里面的PID是否是aria2c，并且其命令行是否是你启动的——如果不是，查看parent PID，检查systemd service还有其他自启动；
3. 采用前台方式启动，查看stdout的报错信息；
4. 服务器上`curl -D - 'http://xx.xx.xx.xx:6800/jsonrpc'`；
5. 考虑aria2版本问题；
6. 考虑ufw防火墙规则。

视情况，有可能某一个、某几个，也可能没有一个能得出结论。这种情况还是找线下或者远程控制比较好（远水不及近火）。
另外，能确认的是“不是webui-aria2”的问题。不妨去[superuser](https://superuser.com/)（英文）或者[server fault](https://serverfault.com/)（英文）或者[segmentfault](https://segmentfault.com/)（中文）问问（记住[提问的艺术](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)）。希望有人能解决你的问题，祝好运。

**Comment by lizhaode** [comment]
非常感谢。
tcpdump我抓包，发现外部访问的时候，是没有数据包的。然后前台启动stdout并没有任何错误信息

我在服务器上 curl -D - 'http://127.0.0.1:6800/jsonrpc' 返回结果是
```
HTTP/1.1 400 Bad Request
Date: Mon, 12 Mar 2018 01:58:49 GMT
Content-Length: 80
Expires: Mon, 12 Mar 2018 01:58:49 GMT
Cache-Control: no-cache
Content-Type: application/json-rpc
Access-Control-Allow-Origin: *
Connection: close

{"id":null,"jsonrpc":"2.0","error":{"code":-32600,"message":"Invalid Request."}}
```

**Comment by no1xsyzy** [comment]
外部访问没有数据包就不是aria2的问题。
tcpdump在防火墙之前生效，所以也不是防火墙问题。
我已经完全没有头绪了。
可能还有一个，考虑VPS控制面板上默认未开启6800端口（导致6800根本不会传入虚拟机）。

@ziahamza Neither WebUI nor aria2 problem. I tried to help but no luck. You can consider closing now.

**Comment by lizhaode** [comment]
所以应该是vps机器的问题吗？很奇怪的是，ss也搭在这个上边，就没问题。我也不知道这种问题应该能从哪里找到帮助

**Comment by no1xsyzy** [comment]
我是真的没有什么思路……要么是上面说的问答社区，要么就是专门的技术支持。VPS提供商应该也提供技术支持，不过应该是另收费。

**Comment by LBYPatrick** [comment]
来解答一下...

我这边的情况:
```
服务器: Linode 东京二区
HTTP软件: lighttpd
服务器系统: Debian 9/Ubuntu 17.10 (都试过，一个效果)
网络: 1Gbps

我: 美国 Verizon, 100Mbps
     学校网络
     广东移动电信联通(暑假测的)
```

这个问题确实很蛋疼，我也是研究了好久才搞定的。

1. 把webui的http端口从80改到81，很多VPS服务商都会对80做限制，我改了之后就没有超时的问题了

我只需要改lightttpd的端口设置就可以了

> 假设你改的也是81...  
> 以后在浏览器里面敲的就是http://<你的服务器>:81

2.如果你设了rpc-user和rpc-passwd的话, 试试在浏览器里面输入``http://<你的服务器>:6800``, 然后按照提示把账号密码输了，然后再回去看看。问题解决

**Comment by no1xsyzy** [comment]
@LBYPatrick 把全文通读两遍，然后把MD修一下

1. 据描述，webui是正常的，就是ws不通；
2. 外部访问无法抵达VPS，内部环回访问可以正常返回token验证，而且user-pass已经不推荐，换token；
3. aria2通常做后台运行，特地用前台运行进行测试，nohup也不方便调试，一般screen吧；

**Comment by zoobop** [comment]
@no1xsyzy 我把防火墙关了，ws就正常连接了，curl -D - 'http://127.0.0.1:6800/jsonrpc' 还是404

**Comment by no1xsyzy** [comment]
@zoobop `curl -D - 'http://127.0.0.1:6800/jsonrpc'` 理论上就应该是400

**Comment by lizhaode** [comment]
感谢大家的帮助，我找到了问题，就是VPS服务商屏蔽掉了6xxx系列的端口
