### ISSUE TITLE
--restart always not work

### ISSUE THREAD

**Issue by softwarevamp** [ziahamza/webui-aria2#447]
after reboot, the download get error, have to restart the container by mannual
Windows 10

**Comment by no1xsyzy** [comment]
Where do you use `--restart` in? Aria2 doesn't accept such parameter.

**Comment by softwarevamp** [comment]
docker run ... -d --restart always ... -v C:\...:/data webui-aria2

**Comment by no1xsyzy** [comment]
Check this: <https://github.com/docker/for-win/issues/1038>, seems to be an upstream issue.
