### ISSUE TITLE
How to make "configuration.js" unreadable for others?

### ISSUE THREAD

**Issue by keks24** [ziahamza/webui-aria2#452]
Hi ziahamza,

I would like to avoid that others can read the `configuration.js` like on this page:

> https://ziahamza.github.io/webui-aria2/configuration.js

I have the following directory structure where owner and group is `webui-aria2`:
```bash
$ getent passwd webui-aria2
webui-aria2:x:4444:4444::/var/www/webui-aria2/:/bin/bash
$ getent group webui-aria2
webui-aria2:x:4444:www-data
```
```
.
|-- README
|-- etc/
|   |-- apache2/
|   |-- aria2/
|   `-- ssl/
|-- htdocs/
|   |-- Dockerfile
|   |-- Dockerfile.arm
|   |-- LICENSE
|   |-- README.md
|   |-- app.json
|   |-- configuration.js
|   |-- css/
|   |-- directurl.md
|   |-- docker-compose.yml
|   |-- favicon.ico
|   |-- flags/
|   |-- fonts/
|   |-- index.html
|   |-- js/
|   |-- node-server.js
|   |-- screenshots/
|   |-- static.json
|   `-- webui-aria2.spec
|-- logs/
|   `-- 2018/
`-- private/
```

I tried the following which always give me a blank page:
```bash
$ cd htdocs
$ chmod 600 configuration.js
```
```bash
$ cd htdocs
$ chown root:root configuration.js
```

Is there any way to secure it properly?
-Ramon

**Comment by no1xsyzy** [comment]
If you want to prevent access to `configuration.js` with HTTP interface, you should configure Apache or Nginx with access IP or something else. Only the server software accesses the file `configuration.js` itself. The browser never accesses the file directly.

**Comment by keks24** [comment]
@no1xsyzy 
Thank you, that worked!

I created a `Files` rule with the following content:
```
<Files "configuration.js">
    <RequireAll>
        Require ip 192.168.2.0/24
    </RequireAll>
</Files>
```

Unfortunately I cannot put a `Require all denied` between the `RequireAll` block, otherwise I get this `403` error:
![screenshot_20180510_155305](https://user-images.githubusercontent.com/13721064/39876686-2757d7b0-5474-11e8-8dae-61d50cf9b09f.png)

A `Redirect 404 /configuration.js` does not work, too. Just the same message but with `403` error:
![screenshot_20180510_162222](https://user-images.githubusercontent.com/13721064/39876775-55646d1c-5474-11e8-8b63-83aa83b6e2e0.png)

**Comment by no1xsyzy** [comment]
I work on Nginx more so I cannot give any help on Apache other than the search engine, sorry.
BTW, if you have found the right way to do that, you can put the method here, which will probably help others who found this issue.
