### ISSUE TITLE
Download halted on finish

### ISSUE THREAD

**Issue by MMrYYx** [ziahamza/webui-aria2#454]
![w oxl032_ ha_ 879ysxt 6](https://user-images.githubusercontent.com/19357184/41504144-cb4d8a4c-7218-11e8-8c18-f33f967f3294.png)

When tasks are finished, they are halted in active state. No download speed, but still uploading somehow.

**Comment by no1xsyzy** [comment]
That's for P2P sharing (other downloaders are downloading with the same torrent). When aria2 is sharing files, it will mark it as an active task. You can stop it and it will become finished (green) state.
See optinos in aria2 manual [`seed-ratio`](https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-seed-ratio) and [`seed-time`](https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-seed-time).
PLZ keep your seed-ratio no smaller than 1 for best sharing.

**Comment by trex005** [comment]
I know this is marked closed but I am having the same issue.

My seed-ratio is 1.0 and seed-time is 0.

I tried giving it a day in case it was finishing some file operations or anything, but it just stays as active.

I have tried pausing an resuming with the same result.

**Comment by anthonyraymond** [comment]
don't set the seed-ratio value (1.0 is the default anyway).

If you intend not to seed at all (which is not nice 😞 ) you have to set the config:
```
seed-time=0
```

If this does not work there is changes that you use an old version of aria2 (you probably got your aria2 version through apt-get, repositories uses outdated version). In this case you'll need a newer version.
