### ISSUE TITLE
[Proposal] Collaborative permission to manage issues

### ISSUE THREAD

**Issue by anthonyraymond** [ziahamza/webui-aria2#458]
Hi @ziahamza ,

As the times goes on, many issues are now irrelevant/outdated or even solved, but aren't closed by the original authors.
If you agree i would like to help you sort this out. You'd need to grant me collaborative permission to the repo. But doing this will also grant other permissions like PR merging, direct push to upstream and some other permissions, so...

It's up to you, but i'd be glad to help you cleaning the issues left open for no reasons.

**Comment by ziahamza** [comment]
I agree that I have not been able to put much time in. And @anthonyraymond  you have shown quite a lot of interest and usage lately. Glad to have you take over as a maintainer 💃

**Comment by anthonyraymond** [comment]
Hey :) thanks.
