### ISSUE TITLE
当批量添加种子的时候，出现这种极端的情况

### ISSUE THREAD

**Issue by moerfutin** [ziahamza/webui-aria2#461]
这些种子的目录结构都相同，处于同一个名称的文件夹之下，除了主要文件以外，还有几个垃圾文件，同时添加批量任务，即使select-files 选项和 pause选项为true，还是下载失败。提示有用样的下载在进行。搞不懂是aria2的锅，还是前端的锅，反正换了2个前端都不可以啊。

> m**et:?xt=urn:b**h:29E841EDF6FEADBE9FAD75AB17507328F50F6493
m**et:?xt=urn:b**h:66FB6C452FB3477137491488A6626BB6B76165A6
m**et:?xt=urn:b**h:0FF4094060ACD09DF7436476E2B5D113627FFF61
m**et:?xt=urn:b**h:299D25465632BFAE66BB9F35C6CAFB3A354ACAE6
m**et:?xt=urn:b**h:3664221CB1A28616368889FC9964527DDA4F02D0
m**et:?xt=urn:b**h:05AC3B4572471257FA8BADBB0376616339DE4357
m**et:?xt=urn:b**h:63716781D0DCEBC0A23C1CD7934B1615FB6C67DC
m**et:?xt=urn:b**h:0F4542BF5A1B2A5DF57BFCF780C0DF78A419D17C
m**et:?xt=urn:b**h:3F8C7975BD65A2F08E3DE74DBE5F53E0392ED1EC
m**et:?xt=urn:b**h:368567F6A75811B78AA9CD35F19C276B01A8B7B0
m**et:?xt=urn:b**h:79A672FE1ED2D38C6B9E51F026B3889612182B36
m**et:?xt=urn:b**h:7AD157FC5E2CE92B4E073E64DDA75409FD57A4D7
m**et:?xt=urn:b**h:62996CBFEE69FE23399623C9CDF88BB5A666840A

**Comment by anthonyraymond** [comment]
Can you write this in english :/ ?
