### ISSUE TITLE
how install aria2 webui on  RASPBIAN STRETCH LITE

### ISSUE THREAD

**Issue by Rohitdk1998** [ziahamza/webui-aria2#478]
I am a beginner of linux.please tell me how install aria2 ui on stretch lite.

**Comment by no1xsyzy** [comment]
If you mean the WebUI, it doesn't need to be installed. Just visit <http://ziahamza.github.io/webui-aria2/> with your browser and input link information of aria2 RPC server.
If you mean aria2, just go <https://aria2.github.io/> to get the answer.

**Comment by Rohitdk1998** [comment]
Thanks
