### ISSUE TITLE
where is the downloaded file ?

### ISSUE THREAD

**Issue by beykery** [ziahamza/webui-aria2#485]
i run aria2 with docker and apply the default config .
then i download a torrent file , but how can i find it ?
the command is :
sudo docker run -d -v /mnt/torrent:/data -p 6800:6800 -p 9100:8080 --name="aria2" william/aria2
but i can not find anything at the path /mnt/torrent
why ?

**Comment by no1xsyzy** [comment]
Did you specify the download destination or `dir` by hand? It can only be in `/data`.
`-v /mnt/torrent:/data` binds `/mnt/torrent` of your host machine with `/data` in the docker image.

**Comment by no1xsyzy** [comment]
There are several things to check with:
1. Does the download actually progress? With 0 bytes, Aria 2 won't write anything.
2. Does writing work. To test, attach to the docker and try `echo test line>/data/TestFile` and see if you can find it in `/mnt/torrent`
If both checks are passed, the problem must be that Aria 2 is not downloading into `/data`. Try specify `dir=/data`.

**Comment by anthonyraymond** [comment]
Closing due to no further answer from the author
