### ISSUE TITLE
How to add multiple header?

### ISSUE THREAD

**Issue by hubutui** [ziahamza/webui-aria2#496]
I've check #163 , but I'm still confused. For eg, my aria2 cmd is :
```bash
aria2c "http://www.example.com" --header "foo" --header "bar"
```
What should I input to header textbox? Furthermore, would you like to add feature to allow copy & paste:
```text
--header "foo" --header "bar"
```
or
```text
-H "foo" -H "bar"
```
to header textbox? `-H` is used in curl, and `aria2c` doesn't have a `-H`, so that one could simply convert curl cmd to aria2.

**Comment by no1xsyzy** [comment]
```
foo
bar
```
just write as if you are writing the HTTP header in the stream.
