### ISSUE TITLE
Torrent completion is not marked properly

### ISSUE THREAD

**Issue by jamadagni** [ziahamza/webui-aria2#505]
I am using current master fb9d758 on Kubuntu Bionic LTS with latest updates and aria2 1.33.1.

After a torrent download is completed, it is not marked as such.

For instance, if I download https://download.documentfoundation.org/libreoffice/stable/6.2.1/deb/x86_64/LibreOffice_6.2.1_Linux_x86-64_deb_helppack_en-US.tar.gz.torrent, first it downloads this file and then processes the torrent itself, which is correct. But even after the `LibreOffice_6.2.1_Linux_x86-64_deb_helppack_en-US.tar.gz` is downloaded, the download is not shown as completed, but download speed and upload speed are 0:

![Screenshot_20190316_113639](https://user-images.githubusercontent.com/948170/54471513-2d506280-47e0-11e9-9104-0eab5188c472.png)

It stays like this indefinitely. Pressing the stop button at this point asks whether I want to delete the data and metadata. Neither does pressing the pause button give a satisfactory result.

Please look into this. Thank you!

BTW I am not sure whether this is related to #274 which has been closed without any comments.

**Comment by no1xsyzy** [comment]
It is by design of aria2, to keep seeding after finished. Stop it would actually make it finished.
See also: aria2 options [`seed-ratio`](https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-seed-ratio) and [`seed-time`](https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-seed-time).

**Comment by jamadagni** [comment]
I feel this has been prematurely closed without considering the problem fully. Please read on:

Certainly I understand the behaviour to keep seeding after it is finished, but I am saying that there is no way to manually stop the seeding of a particular torrent. At the command line using `seed-ratio` or `seed-time` is working correctly, but the settings show that the default value for `seed-time` is `0`:

![Screenshot_20190321_204641](https://user-images.githubusercontent.com/948170/54763689-6e9ba480-4c1c-11e9-92a4-8f95012bfac2.png)

However, this doesn't seem to be actually in effect. As the option description clearly says, if both settings are actually used, the seeding will stop when either of them is satisfied. I just did at the command line:

`aria2c --seed-ratio=0 --seed-time=0 https://download.documentfoundation.org/libreoffice/stable/6.2.2/deb/x86_64/LibreOffice_6.2.2_Linux_x86-64_deb_helppack_en-US.tar.gz.torrent`

and it immediately stopped after downloading because the `--seed-time=0` will always be satisfied earlier than any `--seed-ratio` and in fact evidently it even overrides `--seed-ratio=0` which specifies indefinite seeding.

So it would seem that the options shown in the screenshot aren't actually fed to the aria2 process in the background, but that is perhaps a different bug.

For now, seeing that at the command line I can always cancel an ongoing seeding by Ctrl-C, I am asking for a similar way to cancel seeding and mark the download as done (which "Pause" doesn't do) and retain the downloaded files (which "Stop" doesn't do).

In other graphical torrent clients like KTorrent, the Stop download option doesn't delete the downloaded files of a torrent being seeded but only stops the seeding. Only if I delete an incomplete download am I asked whether I want to delete the incomplete downloaded data as well.

Given that in Aria2 WebUI the stop button is always used to delete downloaded data, maybe the behaviour of the pause button should be changed in the case of torrents being seeded or you can provide yet another button/option to stop seeding.

**Comment by no1xsyzy** [comment]
If you want to manually stop seeding just press stop button.
The warning just means the task and `something.aria2` metadata file. However, the warning will turn it into a finished task rather than remove it.
I understand that this is strange but they cannot be told by the client unless the client checks if it is a torrent task.
