### ISSUE TITLE
Can not download through webui

### ISSUE THREAD

**Issue by nickleefly** [ziahamza/webui-aria2#506]
I run webui-aria2 in a container with
`docker run -d -v /home/nick/drive:/data -p 6800:6800 -p 9100:8080 --name="webui-aria2" nickleefly/webui-aria2`
When I try to add a magnet link from [here](https://www.thepiratebay.org/torrent/32017342/I.Trapped.The.Devil.2019.HDRip.AC3.x264-CMRG[EtMovies]) to download, get the following error
>Exception: [AbstractDiskWriter.cc:222] errNum=13 errorCode=15 Failed to open the file /data/I.Trapped.The.Devil.2019.HDRip.AC3.x264-CMRG[EtMovies]/Downloaded from www.ETTV.tv .txt, cause: Permission denied

**Comment by no1xsyzy** [comment]
Which user do you run `dockerd` with? Have you permitted that user access to `/home/nick/drive`?

**Comment by nickleefly** [comment]
@no1xsyzy I used `root` to run `docker run`

**Comment by nickleefly** [comment]
permission issue, its working

**Comment by oli233** [comment]
How did you sort it mate??

**Comment by oli233** [comment]
> permission issue, its working

What did you do to solve the permission issue?
