### ISSUE TITLE
Oh Snap! Could not connect to the aria2 RPC server. Will retry in 10 secs. You might want to check the connection settings by going to Settings > Connection Settings

### ISSUE THREAD

**Issue by fridayshoes** [ziahamza/webui-aria2#510]
I've just installed this on my GL iNet 300M router and logged into the webui and I see this message being repeated over and over again, any ideas why?

Oh Snap! Could not connect to the aria2 RPC server. Will retry in 10 secs. You might want to check the connection settings by going to Settings > Connection Settings

**Comment by no1xsyzy** [comment]
'cause you haven't set up aria2, to which webui-aria2 is supposed to be connected.
Same for the other issue you've raised

**Comment by fridayshoes** [comment]
I figured that out about 2 hours ago. I wrote down how I solved it here for any other newbs out there, as there doesn't seem to be a simple guide anywhere else.

https://forum.gl-inet.com/t/aria2-and-aria2-web-ui/2111/11

**Comment by szwuzy** [comment]
I have the same question. I don't know if the connection timeout I configured is too short.
My aria2c.exe‘s version is 1.3.5.  It looks ALL is OK too. Pause occasionally.

**Comment by ryoari** [comment]
go the the following link: https://i12bretro.github.io/tutorials/ and type aria2, that should clear all your doubts.
