### ISSUE TITLE
Http response header was bad or unexpect

### ISSUE THREAD

**Issue by ysy1526340881** [ziahamza/webui-aria2#533]
Http response header was bad or unexpect

**Comment by no1xsyzy** [comment]
You should have an running aria2 instance to link to.

**Comment by ysy1526340881** [comment]
hi thank you so much 
I modified the user-agent then it can go work, but the speed has limited, Only 10Kb/s

I change 'userUser-Agent: netdisk;5.3.4.5;PC;PC-Windows;5.1.2600;WindowsBaiduYunGuanJia' to 'netdisk;8.2.0;android-android;4.4.4' 
Does it has some problem?

**Comment by no1xsyzy** [comment]
That's totally not related to `webui-aria2` neither `aria2`. @anthonyraymond plz close.
You should seek where you see this workaround with "baidu net disk", and learn some basic computer knowledge.
