### ISSUE TITLE
parse cURL parameters for aria2 download

### ISSUE THREAD

**Issue by NeverBehave** [ziahamza/webui-aria2#541]
Since most modern browsers(chrome, firefox) support "copy as cURL" in the network tab, I am wondering if anyone interested in having a new feature that parse cURL parameters and download.

Or if anyone has better idea how to extract request(e.g. required cookie, token alone with the request) from browser? I haven't find a neat solution.

**Comment by no1xsyzy** [comment]
Actually, it supports aria2c command line options, using only `--option=something` style, but supports quotes and double-quotes.
And aria2 doesn't support POST downloading.

**Comment by NeverBehave** [comment]
> 
> 
> Actually, it supports aria2c command line options, using only `--option=something` style, but supports quotes and double-quotes.
> And aria2 doesn't support POST downloading.

Yes, but each time I will still have to parse and rebuild the command line options for aria2c. I think somehow it is better to make it a browser extension.
