### ISSUE TITLE
Why does the server return 404

### ISSUE THREAD

**Issue by wkmyws** [ziahamza/webui-aria2#543]
After I started node-server.js , the server show "404 Not Found"

**Comment by Liangwh2001** [comment]
I meet the same problem today. Have you solved the problem yet?

**Comment by wkmyws** [comment]
At last I gave up...




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Liangwh2001"<notifications@github.com&gt;; 
发送时间: 2020年4月23日(星期四) 晚上11:08
收件人: "ziahamza/webui-aria2"<webui-aria2@noreply.github.com&gt;; 
抄送: "wkmyws"<wkmyws@sina.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ziahamza/webui-aria2] Why does the server return 404 (#543)





 
I meet the same problem today. Have you solved the problem yet?

**Comment by JohnnyLAmpAz** [comment]
I also got the same error using NodeJS but then I discovered why:
> Or you can also use NodeJS to create simple server by using the following command **from the project folder**.

You need to run `node node-server.js` directly from the project dir (your `pwd` needs to be the same path of the location of the downloaded repo). Otherwise when you hit the webpage it returns 404 Not Found.
So make sure to `cd /path/to/repo` before starting the node app.

**Comment by agneevX** [comment]
If you're launching via systemd, adding `WorkingDirectory` to the unit file fixes it.

```
[Unit]
Description=webUI aria2 Daemon
After=network.target

[Service]
Type=simple
WorkingDirectory=/opt/webui-aria2
ExecStart=/usr/bin/node /opt/webui-aria2/node-server.js
Restart=on-failure
RestartSec=10
User=agneev
Group=agneev

[Install]
WantedBy=multi-user.target
```

**Comment by mjhd** [comment]
> I also got the same error using NodeJS but then I discovered why:
> 
> > Or you can also use NodeJS to create simple server by using the following command **from the project folder**.
> 
> You need to run `node node-server.js` directly from the project dir (your `pwd` needs to be the same path of the location of the downloaded repo). Otherwise when you hit the webpage it returns 404 Not Found. So make sure to `cd /path/to/repo` before starting the node app.

THANK YOU THANK YOU THANK YOU - KISSES FACE AGGRESSIVELY - I've been tearing my freakin hair out trying to figure out why my start script wasn't working!
