### ISSUE TITLE
How to register webui-aria2 as a magnet protocol handler?

### ISSUE THREAD

**Issue by levicki** [ziahamza/webui-aria2#556]
qBitTorrent webui has an option to register as a protocol handler for magnet links.

After it is registered clicking on a magnet link in your browser automatically opens Add URL dialog.

Does webui-aria2 support that?

If not, any chance it could be added?

**EDIT:** This is what I have in mind

![image](https://user-images.githubusercontent.com/16415478/83669069-3ee27d80-a5d1-11ea-8c16-3f1902467bb4.png)

**Comment by no1xsyzy** [comment]
No, not possible.
It would be a disaster for any web page decide to be system-wise or browser-wise schema handler.
For browser-wise, I think it can be done either with a user script or with a add-on, by catching click event of magnet-ish URLs and prevent direct opening but send message to aria 2 instance after confirm.

**Comment by levicki** [comment]
> It would be a disaster for any web page decide to be system-wise or browser-wise schema handler.

All browsers already support this, otherwise no web applications would be possible.

Furthermore, it requires user consent. You advertise yourself as protocol handler and user gets a prompt which they can refuse.

Please check here for details:
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler/Web-based_protocol_handlers#Registering

I hope you will reconsider once you get familiar with it.

**Comment by no1xsyzy** [comment]
That makes sense, but I am not currently interested. Hope some one can see to it.
If you want do it yourself, you can refer to #417 for how to parse URI, `src/js/app.js` might be where you put register, [`src/js/ctrls/nav.js#L61`](https://github.com/ziahamza/webui-aria2/blob/master/src/js/ctrls/nav.js#L61) should be helpful for showing the download modal. `CONTRIBUTING.md` shows how to build with `npm`.

**Comment by levicki** [comment]
Thanks for considering, and for the explanation. Hopefully someone better equipped for frontend stuff coding will pick it up. It is really not my area of expertise.
