### ISSUE TITLE
Cannot connect to websocket

### ISSUE THREAD

**Issue by winmanjack** [ziahamza/webui-aria2#56]
I have aria2 running in terminal, but when I open the index.html it says the following: Error while talking to aria2 over websocket and gives me no further details. Can I please have some assistance here? And in the terminal all it says is: 
2013-06-22 15:41:56.209883 NOTICE - IPv4 RPC: listening to port 6800

2013-06-22 15:41:56.210544 NOTICE - IPv6 RPC: listening to port 6800

I would love it if I could get some assistance here.

**Comment by anthonyraymond** [comment]
Close seems the issue seems dead (4 years old)
