### ISSUE TITLE
Torrents never show as completed

### ISSUE THREAD

**Issue by gr0undzer0** [ziahamza/webui-aria2#74]
When I download torrents from a magnet link they just say they are waiting. When I click pause all it doesn't pause the waiting torrents. I'd like them to pause when they are finished so I can then purge them later. Also when I reopen the webui all the previously downloaded torrents that I stopped are gone.

**Comment by bartx84** [comment]
i have the same problem, when i download torrents by .torrent the files never show as completed, i must put in pause to continue my download queque

**Comment by anthonyraymond** [comment]
Close seems the issue seems dead (3 years old). And it seems to work for everybody at the time being. Feel free to reopen if you still have issues

**Comment by gilcu3** [comment]
It's not working for me:

Aria2 Version 1.18.8

Features Enabled

    Async DNS
    BitTorrent
    Firefox3 Cookie
    GZip
    HTTPS
    Message Digest
    Metalink
    XML-RPC 

Nor magnet links nor torrents are shown as completed, they stay active forever.

**Comment by anthonyraymond** [comment]
It makes sense, you are using the version 1.18.8, which was released on Sep 11, 2014.

The issue has most ikely been solved on aria2 side from now. The last release as today is 1.34.0, sounds like you are using the apt-get version (which is no longer updated). 

If you want a newer version, you'll have to compile form source.

**Comment by gr0undzer0** [comment]
Thanks!

**Comment by gilcu3** [comment]
@anthonyraymond you are correct, already tested current src version of aria2 and it works as expected :)
